// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: friend.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FriendSvc_CheckIsFriend_FullMethodName = "/FriendSvc/CheckIsFriend"
	FriendSvc_AddFriend_FullMethodName     = "/FriendSvc/AddFriend"
	FriendSvc_GetFriendList_FullMethodName = "/FriendSvc/GetFriendList"
)

// FriendSvcClient is the client API for FriendSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendSvcClient interface {
	// 游戏调用平台，获取一个玩家与一批用户是否是好友关系
	CheckIsFriend(ctx context.Context, in *CheckIsFriendReq, opts ...grpc.CallOption) (*CheckIsFriendResp, error)
	// 申请加好友
	AddFriend(ctx context.Context, in *AddFriendReq, opts ...grpc.CallOption) (*AddFriendResp, error)
	// 获取某个玩家的好友列表
	GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error)
}

type friendSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendSvcClient(cc grpc.ClientConnInterface) FriendSvcClient {
	return &friendSvcClient{cc}
}

func (c *friendSvcClient) CheckIsFriend(ctx context.Context, in *CheckIsFriendReq, opts ...grpc.CallOption) (*CheckIsFriendResp, error) {
	out := new(CheckIsFriendResp)
	err := c.cc.Invoke(ctx, FriendSvc_CheckIsFriend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendSvcClient) AddFriend(ctx context.Context, in *AddFriendReq, opts ...grpc.CallOption) (*AddFriendResp, error) {
	out := new(AddFriendResp)
	err := c.cc.Invoke(ctx, FriendSvc_AddFriend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendSvcClient) GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListResp, error) {
	out := new(GetFriendListResp)
	err := c.cc.Invoke(ctx, FriendSvc_GetFriendList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendSvcServer is the server API for FriendSvc service.
// All implementations must embed UnimplementedFriendSvcServer
// for forward compatibility
type FriendSvcServer interface {
	// 游戏调用平台，获取一个玩家与一批用户是否是好友关系
	CheckIsFriend(context.Context, *CheckIsFriendReq) (*CheckIsFriendResp, error)
	// 申请加好友
	AddFriend(context.Context, *AddFriendReq) (*AddFriendResp, error)
	// 获取某个玩家的好友列表
	GetFriendList(context.Context, *GetFriendListReq) (*GetFriendListResp, error)
	mustEmbedUnimplementedFriendSvcServer()
}

// UnimplementedFriendSvcServer must be embedded to have forward compatible implementations.
type UnimplementedFriendSvcServer struct {
}

func (UnimplementedFriendSvcServer) CheckIsFriend(context.Context, *CheckIsFriendReq) (*CheckIsFriendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIsFriend not implemented")
}
func (UnimplementedFriendSvcServer) AddFriend(context.Context, *AddFriendReq) (*AddFriendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFriend not implemented")
}
func (UnimplementedFriendSvcServer) GetFriendList(context.Context, *GetFriendListReq) (*GetFriendListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendList not implemented")
}
func (UnimplementedFriendSvcServer) mustEmbedUnimplementedFriendSvcServer() {}

// UnsafeFriendSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendSvcServer will
// result in compilation errors.
type UnsafeFriendSvcServer interface {
	mustEmbedUnimplementedFriendSvcServer()
}

func RegisterFriendSvcServer(s grpc.ServiceRegistrar, srv FriendSvcServer) {
	s.RegisterService(&FriendSvc_ServiceDesc, srv)
}

func _FriendSvc_CheckIsFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIsFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendSvcServer).CheckIsFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendSvc_CheckIsFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendSvcServer).CheckIsFriend(ctx, req.(*CheckIsFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendSvc_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendSvcServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendSvc_AddFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendSvcServer).AddFriend(ctx, req.(*AddFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendSvc_GetFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendSvcServer).GetFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendSvc_GetFriendList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendSvcServer).GetFriendList(ctx, req.(*GetFriendListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FriendSvc_ServiceDesc is the grpc.ServiceDesc for FriendSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FriendSvc",
	HandlerType: (*FriendSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIsFriend",
			Handler:    _FriendSvc_CheckIsFriend_Handler,
		},
		{
			MethodName: "AddFriend",
			Handler:    _FriendSvc_AddFriend_Handler,
		},
		{
			MethodName: "GetFriendList",
			Handler:    _FriendSvc_GetFriendList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "friend.proto",
}
