// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: game_mixed.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameMixedSvc_FarmEventPush_FullMethodName  = "/GameMixedSvc/FarmEventPush"
	GameMixedSvc_GetUserNftList_FullMethodName = "/GameMixedSvc/GetUserNftList"
)

// GameMixedSvcClient is the client API for GameMixedSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameMixedSvcClient interface {
	// 农场发送操作事件
	FarmEventPush(ctx context.Context, in *FarmEventPushReq, opts ...grpc.CallOption) (*FarmEventPushResp, error)
	// 获取玩家拥有的 nft 列表
	GetUserNftList(ctx context.Context, in *GetUserNftListReq, opts ...grpc.CallOption) (*GetUserNftListResp, error)
}

type gameMixedSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewGameMixedSvcClient(cc grpc.ClientConnInterface) GameMixedSvcClient {
	return &gameMixedSvcClient{cc}
}

func (c *gameMixedSvcClient) FarmEventPush(ctx context.Context, in *FarmEventPushReq, opts ...grpc.CallOption) (*FarmEventPushResp, error) {
	out := new(FarmEventPushResp)
	err := c.cc.Invoke(ctx, GameMixedSvc_FarmEventPush_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameMixedSvcClient) GetUserNftList(ctx context.Context, in *GetUserNftListReq, opts ...grpc.CallOption) (*GetUserNftListResp, error) {
	out := new(GetUserNftListResp)
	err := c.cc.Invoke(ctx, GameMixedSvc_GetUserNftList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameMixedSvcServer is the server API for GameMixedSvc service.
// All implementations must embed UnimplementedGameMixedSvcServer
// for forward compatibility
type GameMixedSvcServer interface {
	// 农场发送操作事件
	FarmEventPush(context.Context, *FarmEventPushReq) (*FarmEventPushResp, error)
	// 获取玩家拥有的 nft 列表
	GetUserNftList(context.Context, *GetUserNftListReq) (*GetUserNftListResp, error)
	mustEmbedUnimplementedGameMixedSvcServer()
}

// UnimplementedGameMixedSvcServer must be embedded to have forward compatible implementations.
type UnimplementedGameMixedSvcServer struct {
}

func (UnimplementedGameMixedSvcServer) FarmEventPush(context.Context, *FarmEventPushReq) (*FarmEventPushResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FarmEventPush not implemented")
}
func (UnimplementedGameMixedSvcServer) GetUserNftList(context.Context, *GetUserNftListReq) (*GetUserNftListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserNftList not implemented")
}
func (UnimplementedGameMixedSvcServer) mustEmbedUnimplementedGameMixedSvcServer() {}

// UnsafeGameMixedSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameMixedSvcServer will
// result in compilation errors.
type UnsafeGameMixedSvcServer interface {
	mustEmbedUnimplementedGameMixedSvcServer()
}

func RegisterGameMixedSvcServer(s grpc.ServiceRegistrar, srv GameMixedSvcServer) {
	s.RegisterService(&GameMixedSvc_ServiceDesc, srv)
}

func _GameMixedSvc_FarmEventPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FarmEventPushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameMixedSvcServer).FarmEventPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameMixedSvc_FarmEventPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameMixedSvcServer).FarmEventPush(ctx, req.(*FarmEventPushReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameMixedSvc_GetUserNftList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNftListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameMixedSvcServer).GetUserNftList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameMixedSvc_GetUserNftList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameMixedSvcServer).GetUserNftList(ctx, req.(*GetUserNftListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameMixedSvc_ServiceDesc is the grpc.ServiceDesc for GameMixedSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameMixedSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GameMixedSvc",
	HandlerType: (*GameMixedSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FarmEventPush",
			Handler:    _GameMixedSvc_FarmEventPush_Handler,
		},
		{
			MethodName: "GetUserNftList",
			Handler:    _GameMixedSvc_GetUserNftList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_mixed.proto",
}
