// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: game_interaction.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumeEnergyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识，eg:1跑酷 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId string `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 关卡、难度级别的 id | @inject_tag: msgpack:"levelId" json:"levelId"
	LevelId int64 `protobuf:"varint,2,opt,name=levelId,proto3" json:"levelId" msgpack:"levelId"`
	// 关卡、难度级别的 id | @inject_tag: msgpack:"needEnergy" json:"needEnergy"
	NeedEnergy int32 `protobuf:"varint,3,opt,name=needEnergy,proto3" json:"needEnergy" msgpack:"needEnergy"`
	// 玩家的 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
}

func (x *ConsumeEnergyReq) Reset() {
	*x = ConsumeEnergyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeEnergyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEnergyReq) ProtoMessage() {}

func (x *ConsumeEnergyReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeEnergyReq.ProtoReflect.Descriptor instead.
func (*ConsumeEnergyReq) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumeEnergyReq) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ConsumeEnergyReq) GetLevelId() int64 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *ConsumeEnergyReq) GetNeedEnergy() int32 {
	if x != nil {
		return x.NeedEnergy
	}
	return 0
}

func (x *ConsumeEnergyReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ConsumeEnergyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
}

func (x *ConsumeEnergyResp) Reset() {
	*x = ConsumeEnergyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeEnergyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEnergyResp) ProtoMessage() {}

func (x *ConsumeEnergyResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeEnergyResp.ProtoReflect.Descriptor instead.
func (*ConsumeEnergyResp) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeEnergyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConsumeEnergyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GameCallbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 对局 id | @inject_tag: msgpack:"battleId" json:"battleId"
	BattleId int64 `protobuf:"varint,1,opt,name=battleId,proto3" json:"battleId" msgpack:"battleId"`
	// 结算时的玩家数据 | @inject_tag: msgpack:"playerRankReqDtoList" json:"playerRankReqDtoList"
	PlayerRankReqDtoList []*PlayerDtoListItem `protobuf:"bytes,2,rep,name=playerRankReqDtoList,proto3" json:"playerRankReqDtoList" msgpack:"playerRankReqDtoList"`
}

func (x *GameCallbackReq) Reset() {
	*x = GameCallbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCallbackReq) ProtoMessage() {}

func (x *GameCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCallbackReq.ProtoReflect.Descriptor instead.
func (*GameCallbackReq) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *GameCallbackReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *GameCallbackReq) GetPlayerRankReqDtoList() []*PlayerDtoListItem {
	if x != nil {
		return x.PlayerRankReqDtoList
	}
	return nil
}

type PlayerDtoListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户 id | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
	// 使用的 nft。考虑多 nftId 的情况？ | @inject_tag: msgpack:"nftId" json:"nftId"
	NftId int32 `protobuf:"varint,2,opt,name=nftId,proto3" json:"nftId" msgpack:"nftId"`
	// 奖励系数 | @inject_tag: msgpack:"rewardCoefficient" json:"rewardCoefficient"
	RewardCoefficient int32 `protobuf:"varint,3,opt,name=rewardCoefficient,proto3" json:"rewardCoefficient" msgpack:"rewardCoefficient"`
	// 排名 | @inject_tag: msgpack:"rank" json:"rank"
	Rank int32 `protobuf:"varint,4,opt,name=rank,proto3" json:"rank" msgpack:"rank"`
	// 关卡 | @inject_tag: msgpack:"stage" json:"stage"
	Stage int32 `protobuf:"varint,5,opt,name=stage,proto3" json:"stage" msgpack:"stage"`
	// 进度。不同游戏对应的属性不同，可能是：波次，关卡，积分等 | @inject_tag: msgpack:"point" json:"point"
	Point int32 `protobuf:"varint,6,opt,name=point,proto3" json:"point" msgpack:"point"`
	// 获得的符文 map | @inject_tag: msgpack:"runes" json:"runes"
	Runes map[string]int32 `protobuf:"bytes,7,rep,name=runes,proto3" json:"runes" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" msgpack:"runes"`
	// 奖励的体力值 | @inject_tag: msgpack:"energy" json:"energy"
	Energy int32 `protobuf:"varint,8,opt,name=energy,proto3" json:"energy" msgpack:"energy"`
	// 奖励的 GP | @inject_tag: msgpack:"token" json:"token"
	Token string `protobuf:"bytes,9,opt,name=token,proto3" json:"token" msgpack:"token"`
	// 当前关卡消耗的体力值 | @inject_tag: msgpack:"consumeEnergy" json:"consumeEnergy"
	ConsumeEnergy int32 `protobuf:"varint,10,opt,name=consumeEnergy,proto3" json:"consumeEnergy" msgpack:"consumeEnergy"`
	// 输赢状态。对于 uid，胜负状态。1胜利，2失败 | @inject_tag: msgpack:"winStatus" json:"winStatus"
	WinStatus int32 `protobuf:"varint,11,opt,name=winStatus,proto3" json:"winStatus" msgpack:"winStatus"`
	// 对局时长，秒数 | @inject_tag: msgpack:"gameTimeSec" json:"gameTimeSec"
	GameTimeSec int32 `protobuf:"varint,12,opt,name=gameTimeSec,proto3" json:"gameTimeSec" msgpack:"gameTimeSec"`
	// 难度。特殊的筛选条件,没有传0。
	// 指定难度下，玩家最佳成绩 | @inject_tag: msgpack:"difficulty" json:"difficulty"
	Difficulty int32 `protobuf:"varint,13,opt,name=difficulty,proto3" json:"difficulty" msgpack:"difficulty"`
}

func (x *PlayerDtoListItem) Reset() {
	*x = PlayerDtoListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerDtoListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDtoListItem) ProtoMessage() {}

func (x *PlayerDtoListItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDtoListItem.ProtoReflect.Descriptor instead.
func (*PlayerDtoListItem) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerDtoListItem) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PlayerDtoListItem) GetNftId() int32 {
	if x != nil {
		return x.NftId
	}
	return 0
}

func (x *PlayerDtoListItem) GetRewardCoefficient() int32 {
	if x != nil {
		return x.RewardCoefficient
	}
	return 0
}

func (x *PlayerDtoListItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *PlayerDtoListItem) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *PlayerDtoListItem) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *PlayerDtoListItem) GetRunes() map[string]int32 {
	if x != nil {
		return x.Runes
	}
	return nil
}

func (x *PlayerDtoListItem) GetEnergy() int32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *PlayerDtoListItem) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PlayerDtoListItem) GetConsumeEnergy() int32 {
	if x != nil {
		return x.ConsumeEnergy
	}
	return 0
}

func (x *PlayerDtoListItem) GetWinStatus() int32 {
	if x != nil {
		return x.WinStatus
	}
	return 0
}

func (x *PlayerDtoListItem) GetGameTimeSec() int32 {
	if x != nil {
		return x.GameTimeSec
	}
	return 0
}

func (x *PlayerDtoListItem) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

type GameCallbackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
}

func (x *GameCallbackResp) Reset() {
	*x = GameCallbackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCallbackResp) ProtoMessage() {}

func (x *GameCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCallbackResp.ProtoReflect.Descriptor instead.
func (*GameCallbackResp) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *GameCallbackResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GameCallbackResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GameSessCallbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户 id | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
	// 对局 id | @inject_tag: msgpack:"battleId" json:"battleId"
	BattleId int64 `protobuf:"varint,2,opt,name=battleId,proto3" json:"battleId" msgpack:"battleId"`
	// 奖励系数 | @inject_tag: msgpack:"rewardCoefficient" json:"rewardCoefficient"
	RewardCoefficient float32 `protobuf:"fixed32,3,opt,name=rewardCoefficient,proto3" json:"rewardCoefficient" msgpack:"rewardCoefficient"`
	// 是否获取推荐的场次信息 | @inject_tag: msgpack:"isRecommend" json:"isRecommend"
	IsRecommend bool `protobuf:"varint,4,opt,name=isRecommend,proto3" json:"isRecommend" msgpack:"isRecommend"`
	// 1v1 时的玩家排名；
	Rank int32 `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *GameSessCallbackReq) Reset() {
	*x = GameSessCallbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameSessCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSessCallbackReq) ProtoMessage() {}

func (x *GameSessCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSessCallbackReq.ProtoReflect.Descriptor instead.
func (*GameSessCallbackReq) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *GameSessCallbackReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GameSessCallbackReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *GameSessCallbackReq) GetRewardCoefficient() float32 {
	if x != nil {
		return x.RewardCoefficient
	}
	return 0
}

func (x *GameSessCallbackReq) GetIsRecommend() bool {
	if x != nil {
		return x.IsRecommend
	}
	return false
}

func (x *GameSessCallbackReq) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GameSessCallbackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
	// 推荐场次信息相关数据 | @inject_tag: msgpack:"data" json:"data"
	Data *GameSessCallbackRespData `protobuf:"bytes,3,opt,name=data,proto3" json:"data" msgpack:"data"`
}

func (x *GameSessCallbackResp) Reset() {
	*x = GameSessCallbackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameSessCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSessCallbackResp) ProtoMessage() {}

func (x *GameSessCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSessCallbackResp.ProtoReflect.Descriptor instead.
func (*GameSessCallbackResp) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *GameSessCallbackResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GameSessCallbackResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameSessCallbackResp) GetData() *GameSessCallbackRespData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GameSessCallbackRespData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏场 id | @inject_tag: msgpack:"lobbyId" json:"lobbyId"
	LobbyId int32 `protobuf:"varint,1,opt,name=lobbyId,proto3" json:"lobbyId" msgpack:"lobbyId"`
	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 游戏标识 | @inject_tag: msgpack:"mode" json:"mode"
	Mode string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode" msgpack:"mode"`
	// 游戏标识名 | @inject_tag: msgpack:"modeName" json:"modeName"
	ModeName string `protobuf:"bytes,4,opt,name=modeName,proto3" json:"modeName" msgpack:"modeName"`
	// 推荐的场次的消耗类型，这里是门票 | @inject_tag: msgpack:"consumeType" json:"consumeType"
	ConsumeType string `protobuf:"bytes,5,opt,name=consumeType,proto3" json:"consumeType" msgpack:"consumeType"`
	// 推荐的场次的门票数 | @inject_tag: msgpack:"consumeValue" json:"consumeValue"
	ConsumeValue string `protobuf:"bytes,6,opt,name=consumeValue,proto3" json:"consumeValue" msgpack:"consumeValue"`
	// 推荐的场次的奖励类型，这里是 token | @inject_tag: msgpack:"rewardType" json:"rewardType"
	RewardType string `protobuf:"bytes,7,opt,name=rewardType,proto3" json:"rewardType" msgpack:"rewardType"`
	// 推荐的场次的奖品数值 | @inject_tag: msgpack:"rewardValue" json:"rewardValue"
	RewardValue string `protobuf:"bytes,8,opt,name=rewardValue,proto3" json:"rewardValue" msgpack:"rewardValue"`
	// 推荐的场次的图片 | @inject_tag: msgpack:"bannerImg" json:"bannerImg"
	BannerImg string `protobuf:"bytes,9,opt,name=bannerImg,proto3" json:"bannerImg" msgpack:"bannerImg"`
	// 当前玩家的任务进度信息 | @inject_tag: msgpack:"taskInfos" json:"taskInfos"
	TaskInfos []*TaskInfoItem `protobuf:"bytes,10,rep,name=taskInfos,proto3" json:"taskInfos" msgpack:"taskInfos"`
	// nft 对应的分数 | @inject_tag: msgpack:"score" json:"score"
	Score int32 `protobuf:"varint,11,opt,name=score,proto3" json:"score" msgpack:"score"`
	// 1v1 时玩家得到的 GP 奖励 | @inject_tag: msgpack:"reward" json:"reward"
	Reward string `protobuf:"bytes,12,opt,name=reward,proto3" json:"reward" msgpack:"reward"`
	// 与 gameId 对应，一款游戏的名字 | @inject_tag: msgpack:"gameName" json:"gameName"
	GameName string `protobuf:"bytes,13,opt,name=gameName,proto3" json:"gameName" msgpack:"gameName"`
}

func (x *GameSessCallbackRespData) Reset() {
	*x = GameSessCallbackRespData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameSessCallbackRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSessCallbackRespData) ProtoMessage() {}

func (x *GameSessCallbackRespData) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSessCallbackRespData.ProtoReflect.Descriptor instead.
func (*GameSessCallbackRespData) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *GameSessCallbackRespData) GetLobbyId() int32 {
	if x != nil {
		return x.LobbyId
	}
	return 0
}

func (x *GameSessCallbackRespData) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameSessCallbackRespData) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GameSessCallbackRespData) GetModeName() string {
	if x != nil {
		return x.ModeName
	}
	return ""
}

func (x *GameSessCallbackRespData) GetConsumeType() string {
	if x != nil {
		return x.ConsumeType
	}
	return ""
}

func (x *GameSessCallbackRespData) GetConsumeValue() string {
	if x != nil {
		return x.ConsumeValue
	}
	return ""
}

func (x *GameSessCallbackRespData) GetRewardType() string {
	if x != nil {
		return x.RewardType
	}
	return ""
}

func (x *GameSessCallbackRespData) GetRewardValue() string {
	if x != nil {
		return x.RewardValue
	}
	return ""
}

func (x *GameSessCallbackRespData) GetBannerImg() string {
	if x != nil {
		return x.BannerImg
	}
	return ""
}

func (x *GameSessCallbackRespData) GetTaskInfos() []*TaskInfoItem {
	if x != nil {
		return x.TaskInfos
	}
	return nil
}

func (x *GameSessCallbackRespData) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GameSessCallbackRespData) GetReward() string {
	if x != nil {
		return x.Reward
	}
	return ""
}

func (x *GameSessCallbackRespData) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

type TaskInfoItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 任务文案 | @inject_tag: msgpack:"taskDetail" json:"taskDetail"
	TaskDetail string `protobuf:"bytes,1,opt,name=taskDetail,proto3" json:"taskDetail" msgpack:"taskDetail"`
	// 已完成数量 | @inject_tag: msgpack:"goingNumber" json:"goingNumber"
	GoingNumber string `protobuf:"bytes,2,opt,name=goingNumber,proto3" json:"goingNumber" msgpack:"goingNumber"`
	// 该任务的子任务总数 | @inject_tag: msgpack:"total" json:"total"
	Total string `protobuf:"bytes,3,opt,name=total,proto3" json:"total" msgpack:"total"`
	// 任务是否完成 | @inject_tag: msgpack:"isCompleted" json:"isCompleted"
	IsCompleted bool `protobuf:"varint,4,opt,name=isCompleted,proto3" json:"isCompleted" msgpack:"isCompleted"`
}

func (x *TaskInfoItem) Reset() {
	*x = TaskInfoItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoItem) ProtoMessage() {}

func (x *TaskInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoItem.ProtoReflect.Descriptor instead.
func (*TaskInfoItem) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *TaskInfoItem) GetTaskDetail() string {
	if x != nil {
		return x.TaskDetail
	}
	return ""
}

func (x *TaskInfoItem) GetGoingNumber() string {
	if x != nil {
		return x.GoingNumber
	}
	return ""
}

func (x *TaskInfoItem) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *TaskInfoItem) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

type PvpKnockoutSettleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 对局 id | @inject_tag: msgpack:"battleId" json:"battleId"
	BattleId int64 `protobuf:"varint,1,opt,name=battleId,proto3" json:"battleId" msgpack:"battleId"`
	// 用户 id，胜方 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
	// 对手 uid，败方的 uid | @inject_tag: msgpack:"competitorId" json:"competitorId"
	CompetitorId string `protobuf:"bytes,3,opt,name=competitorId,proto3" json:"competitorId" msgpack:"competitorId"`
	// 胜方对应的 nftId | @inject_tag: msgpack:"nftId" json:"nftId"
	NftId int64 `protobuf:"varint,4,opt,name=nftId,proto3" json:"nftId" msgpack:"nftId"`
	// 败方对应的 nftId | @inject_tag: msgpack:"competitorNftId" json:"competitorNftId"
	CompetitorNftId int64 `protobuf:"varint,5,opt,name=competitorNftId,proto3" json:"competitorNftId" msgpack:"competitorNftId"`
}

func (x *PvpKnockoutSettleReq) Reset() {
	*x = PvpKnockoutSettleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PvpKnockoutSettleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpKnockoutSettleReq) ProtoMessage() {}

func (x *PvpKnockoutSettleReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpKnockoutSettleReq.ProtoReflect.Descriptor instead.
func (*PvpKnockoutSettleReq) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *PvpKnockoutSettleReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *PvpKnockoutSettleReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PvpKnockoutSettleReq) GetCompetitorId() string {
	if x != nil {
		return x.CompetitorId
	}
	return ""
}

func (x *PvpKnockoutSettleReq) GetNftId() int64 {
	if x != nil {
		return x.NftId
	}
	return 0
}

func (x *PvpKnockoutSettleReq) GetCompetitorNftId() int64 {
	if x != nil {
		return x.CompetitorNftId
	}
	return 0
}

type PvpKnockoutSettleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
}

func (x *PvpKnockoutSettleResp) Reset() {
	*x = PvpKnockoutSettleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PvpKnockoutSettleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpKnockoutSettleResp) ProtoMessage() {}

func (x *PvpKnockoutSettleResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpKnockoutSettleResp.ProtoReflect.Descriptor instead.
func (*PvpKnockoutSettleResp) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *PvpKnockoutSettleResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PvpKnockoutSettleResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GamePveNextReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 对局 id | @inject_tag: msgpack:"battleId" json:"battleId"
	BattleId int64 `protobuf:"varint,1,opt,name=battleId,proto3" json:"battleId" msgpack:"battleId"`
}

func (x *GamePveNextReq) Reset() {
	*x = GamePveNextReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamePveNextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePveNextReq) ProtoMessage() {}

func (x *GamePveNextReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePveNextReq.ProtoReflect.Descriptor instead.
func (*GamePveNextReq) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{11}
}

func (x *GamePveNextReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

type GamePveNextResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
}

func (x *GamePveNextResp) Reset() {
	*x = GamePveNextResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_interaction_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamePveNextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePveNextResp) ProtoMessage() {}

func (x *GamePveNextResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_interaction_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePveNextResp.ProtoReflect.Descriptor instead.
func (*GamePveNextResp) Descriptor() ([]byte, []int) {
	return file_game_interaction_proto_rawDescGZIP(), []int{12}
}

func (x *GamePveNextResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GamePveNextResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_game_interaction_proto protoreflect.FileDescriptor

var file_game_interaction_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x6e, 0x65, 0x65, 0x64, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6e, 0x65, 0x65, 0x64, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x22, 0x41, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x75, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x46, 0x0a, 0x14, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b,
	0x52, 0x65, 0x71, 0x44, 0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x14, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b,
	0x52, 0x65, 0x71, 0x44, 0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xcc, 0x03, 0x0a, 0x11, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x11, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66,
	0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x05, 0x72, 0x75, 0x6e, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x74,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x52, 0x75, 0x6e, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x72, 0x75, 0x6e, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6e, 0x65,
	0x72, 0x67, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x77, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x77, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x1a,
	0x38, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x10, 0x47, 0x61, 0x6d,
	0x65, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x13,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66,
	0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x11, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x65, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x73, 0x0a, 0x14, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x73,
	0x73, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x65, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x99, 0x03, 0x0a, 0x18, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x6d, 0x67, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x6d, 0x67, 0x12,
	0x2b, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x73,
	0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x6f, 0x69, 0x6e, 0x67,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x6f,
	0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x22, 0xa8, 0x01, 0x0a, 0x14, 0x50, 0x76, 0x70, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70,
	0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x66, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6e, 0x66, 0x74,
	0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72,
	0x4e, 0x66, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x6f, 0x6d,
	0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x4e, 0x66, 0x74, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x15,
	0x50, 0x76, 0x70, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x74, 0x74, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x76, 0x65, 0x4e, 0x65,
	0x78, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x64, 0x22, 0x3f, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x76, 0x65, 0x4e, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0xc2, 0x02, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x76, 0x63, 0x12, 0x38, 0x0a, 0x0d, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x12, 0x11, 0x2e, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x12, 0x10, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x10, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x14,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x73, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x73, 0x73, 0x43,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x44, 0x0a,
	0x11, 0x50, 0x76, 0x70, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x74, 0x74,
	0x6c, 0x65, 0x12, 0x15, 0x2e, 0x50, 0x76, 0x70, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74,
	0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x50, 0x76, 0x70, 0x4b,
	0x6e, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x76, 0x65, 0x4e, 0x65,
	0x78, 0x74, 0x12, 0x0f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x76, 0x65, 0x4e, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x76, 0x65, 0x4e, 0x65, 0x78,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x64, 0x5a, 0x62, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x68, 0x61, 0x6e, 0x79, 0x75, 0x6a, 0x69, 0x65,
	0x2f, 0x67, 0x6f, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x76,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2f, 0x70, 0x62, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_interaction_proto_rawDescOnce sync.Once
	file_game_interaction_proto_rawDescData = file_game_interaction_proto_rawDesc
)

func file_game_interaction_proto_rawDescGZIP() []byte {
	file_game_interaction_proto_rawDescOnce.Do(func() {
		file_game_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_interaction_proto_rawDescData)
	})
	return file_game_interaction_proto_rawDescData
}

var file_game_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_game_interaction_proto_goTypes = []interface{}{
	(*ConsumeEnergyReq)(nil),         // 0: ConsumeEnergyReq
	(*ConsumeEnergyResp)(nil),        // 1: ConsumeEnergyResp
	(*GameCallbackReq)(nil),          // 2: GameCallbackReq
	(*PlayerDtoListItem)(nil),        // 3: PlayerDtoListItem
	(*GameCallbackResp)(nil),         // 4: GameCallbackResp
	(*GameSessCallbackReq)(nil),      // 5: GameSessCallbackReq
	(*GameSessCallbackResp)(nil),     // 6: GameSessCallbackResp
	(*GameSessCallbackRespData)(nil), // 7: GameSessCallbackRespData
	(*TaskInfoItem)(nil),             // 8: TaskInfoItem
	(*PvpKnockoutSettleReq)(nil),     // 9: PvpKnockoutSettleReq
	(*PvpKnockoutSettleResp)(nil),    // 10: PvpKnockoutSettleResp
	(*GamePveNextReq)(nil),           // 11: GamePveNextReq
	(*GamePveNextResp)(nil),          // 12: GamePveNextResp
	nil,                              // 13: PlayerDtoListItem.RunesEntry
}
var file_game_interaction_proto_depIdxs = []int32{
	3,  // 0: GameCallbackReq.playerRankReqDtoList:type_name -> PlayerDtoListItem
	13, // 1: PlayerDtoListItem.runes:type_name -> PlayerDtoListItem.RunesEntry
	7,  // 2: GameSessCallbackResp.data:type_name -> GameSessCallbackRespData
	8,  // 3: GameSessCallbackRespData.taskInfos:type_name -> TaskInfoItem
	0,  // 4: GameInteractionSvc.ConsumeEnergy:input_type -> ConsumeEnergyReq
	2,  // 5: GameInteractionSvc.GameCallback:input_type -> GameCallbackReq
	5,  // 6: GameInteractionSvc.GameSessCallback:input_type -> GameSessCallbackReq
	9,  // 7: GameInteractionSvc.PvpKnockoutSettle:input_type -> PvpKnockoutSettleReq
	11, // 8: GameInteractionSvc.GamePveNext:input_type -> GamePveNextReq
	1,  // 9: GameInteractionSvc.ConsumeEnergy:output_type -> ConsumeEnergyResp
	4,  // 10: GameInteractionSvc.GameCallback:output_type -> GameCallbackResp
	6,  // 11: GameInteractionSvc.GameSessCallback:output_type -> GameSessCallbackResp
	10, // 12: GameInteractionSvc.PvpKnockoutSettle:output_type -> PvpKnockoutSettleResp
	12, // 13: GameInteractionSvc.GamePveNext:output_type -> GamePveNextResp
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_game_interaction_proto_init() }
func file_game_interaction_proto_init() {
	if File_game_interaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_interaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeEnergyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeEnergyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCallbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerDtoListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCallbackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameSessCallbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameSessCallbackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameSessCallbackRespData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfoItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PvpKnockoutSettleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PvpKnockoutSettleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamePveNextReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_interaction_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamePveNextResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_interaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_interaction_proto_goTypes,
		DependencyIndexes: file_game_interaction_proto_depIdxs,
		MessageInfos:      file_game_interaction_proto_msgTypes,
	}.Build()
	File_game_interaction_proto = out.File
	file_game_interaction_proto_rawDesc = nil
	file_game_interaction_proto_goTypes = nil
	file_game_interaction_proto_depIdxs = nil
}
