// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: game_mixed.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserNftListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 玩家 id | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
}

func (x *GetUserNftListReq) Reset() {
	*x = GetUserNftListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_mixed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserNftListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNftListReq) ProtoMessage() {}

func (x *GetUserNftListReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_mixed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNftListReq.ProtoReflect.Descriptor instead.
func (*GetUserNftListReq) Descriptor() ([]byte, []int) {
	return file_game_mixed_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserNftListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetUserNftListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
	// 玩家拥有的 nft 列表 | @inject_tag: msgpack:"nftList" json:"nftList"
	NftList []*Nft `protobuf:"bytes,3,rep,name=nftList,proto3" json:"nftList" msgpack:"nftList"`
}

func (x *GetUserNftListResp) Reset() {
	*x = GetUserNftListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_mixed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserNftListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNftListResp) ProtoMessage() {}

func (x *GetUserNftListResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_mixed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNftListResp.ProtoReflect.Descriptor instead.
func (*GetUserNftListResp) Descriptor() ([]byte, []int) {
	return file_game_mixed_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserNftListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserNftListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserNftListResp) GetNftList() []*Nft {
	if x != nil {
		return x.NftList
	}
	return nil
}

type Nft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// nft id | @inject_tag: msgpack:"nftId" json:"nftId"
	NftId int32 `protobuf:"varint,1,opt,name=nftId,proto3" json:"nftId" msgpack:"nftId"`
}

func (x *Nft) Reset() {
	*x = Nft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_mixed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nft) ProtoMessage() {}

func (x *Nft) ProtoReflect() protoreflect.Message {
	mi := &file_game_mixed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nft.ProtoReflect.Descriptor instead.
func (*Nft) Descriptor() ([]byte, []int) {
	return file_game_mixed_proto_rawDescGZIP(), []int{2}
}

func (x *Nft) GetNftId() int32 {
	if x != nil {
		return x.NftId
	}
	return 0
}

type FarmEventPushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户的 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
	// 类型（1：收获 2：种植 3：天灾人祸 4:开垦土地 5:购买礼包 6:与神秘商人交易）| @inject_tag: msgpack:"typ" json:"typ"
	Typ int32 `protobuf:"varint,2,opt,name=typ,proto3" json:"typ" msgpack:"typ"`
	// 类型对应的值。eg:类型为6时，值就是交易的 gp 数 | @inject_tag: msgpack:"value" json:"value"
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value" msgpack:"value"`
}

func (x *FarmEventPushReq) Reset() {
	*x = FarmEventPushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_mixed_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FarmEventPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmEventPushReq) ProtoMessage() {}

func (x *FarmEventPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_mixed_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmEventPushReq.ProtoReflect.Descriptor instead.
func (*FarmEventPushReq) Descriptor() ([]byte, []int) {
	return file_game_mixed_proto_rawDescGZIP(), []int{3}
}

func (x *FarmEventPushReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FarmEventPushReq) GetTyp() int32 {
	if x != nil {
		return x.Typ
	}
	return 0
}

func (x *FarmEventPushReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FarmEventPushResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
}

func (x *FarmEventPushResp) Reset() {
	*x = FarmEventPushResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_mixed_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FarmEventPushResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarmEventPushResp) ProtoMessage() {}

func (x *FarmEventPushResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_mixed_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarmEventPushResp.ProtoReflect.Descriptor instead.
func (*FarmEventPushResp) Descriptor() ([]byte, []int) {
	return file_game_mixed_proto_rawDescGZIP(), []int{4}
}

func (x *FarmEventPushResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FarmEventPushResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_game_mixed_proto protoreflect.FileDescriptor

var file_game_mixed_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d, 0x69, 0x78, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x25, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x66, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x62, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a,
	0x07, 0x6e, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04,
	0x2e, 0x4e, 0x66, 0x74, 0x52, 0x07, 0x6e, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x1b, 0x0a,
	0x03, 0x4e, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x10, 0x46, 0x61,
	0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74,
	0x79, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x41, 0x0a, 0x11, 0x46, 0x61, 0x72, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x85, 0x01, 0x0a, 0x0c,
	0x47, 0x61, 0x6d, 0x65, 0x4d, 0x69, 0x78, 0x65, 0x64, 0x53, 0x76, 0x63, 0x12, 0x38, 0x0a, 0x0d,
	0x46, 0x61, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x73, 0x68, 0x12, 0x11, 0x2e,
	0x46, 0x61, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x46, 0x61, 0x72, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x42, 0x64, 0x5a, 0x62, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x75, 0x68, 0x61, 0x6e, 0x79, 0x75, 0x6a, 0x69, 0x65, 0x2f, 0x67, 0x6f, 0x5f,
	0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x2f, 0x70, 0x62, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_game_mixed_proto_rawDescOnce sync.Once
	file_game_mixed_proto_rawDescData = file_game_mixed_proto_rawDesc
)

func file_game_mixed_proto_rawDescGZIP() []byte {
	file_game_mixed_proto_rawDescOnce.Do(func() {
		file_game_mixed_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_mixed_proto_rawDescData)
	})
	return file_game_mixed_proto_rawDescData
}

var file_game_mixed_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_game_mixed_proto_goTypes = []interface{}{
	(*GetUserNftListReq)(nil),  // 0: GetUserNftListReq
	(*GetUserNftListResp)(nil), // 1: GetUserNftListResp
	(*Nft)(nil),                // 2: Nft
	(*FarmEventPushReq)(nil),   // 3: FarmEventPushReq
	(*FarmEventPushResp)(nil),  // 4: FarmEventPushResp
}
var file_game_mixed_proto_depIdxs = []int32{
	2, // 0: GetUserNftListResp.nftList:type_name -> Nft
	3, // 1: GameMixedSvc.FarmEventPush:input_type -> FarmEventPushReq
	0, // 2: GameMixedSvc.GetUserNftList:input_type -> GetUserNftListReq
	4, // 3: GameMixedSvc.FarmEventPush:output_type -> FarmEventPushResp
	1, // 4: GameMixedSvc.GetUserNftList:output_type -> GetUserNftListResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_mixed_proto_init() }
func file_game_mixed_proto_init() {
	if File_game_mixed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_mixed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserNftListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_mixed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserNftListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_mixed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_mixed_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FarmEventPushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_mixed_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FarmEventPushResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_mixed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_mixed_proto_goTypes,
		DependencyIndexes: file_game_mixed_proto_depIdxs,
		MessageInfos:      file_game_mixed_proto_msgTypes,
	}.Build()
	File_game_mixed_proto = out.File
	file_game_mixed_proto_rawDesc = nil
	file_game_mixed_proto_goTypes = nil
	file_game_mixed_proto_depIdxs = nil
}
