// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: game_interaction.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameInteractionSvc_ConsumeEnergy_FullMethodName     = "/GameInteractionSvc/ConsumeEnergy"
	GameInteractionSvc_GameCallback_FullMethodName      = "/GameInteractionSvc/GameCallback"
	GameInteractionSvc_GameSessCallback_FullMethodName  = "/GameInteractionSvc/GameSessCallback"
	GameInteractionSvc_PvpKnockoutSettle_FullMethodName = "/GameInteractionSvc/PvpKnockoutSettle"
	GameInteractionSvc_GamePveNext_FullMethodName       = "/GameInteractionSvc/GamePveNext"
)

// GameInteractionSvcClient is the client API for GameInteractionSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameInteractionSvcClient interface {
	// 消耗体力值
	ConsumeEnergy(ctx context.Context, in *ConsumeEnergyReq, opts ...grpc.CallOption) (*ConsumeEnergyResp, error)
	// game over callback
	GameCallback(ctx context.Context, in *GameCallbackReq, opts ...grpc.CallOption) (*GameCallbackResp, error)
	// game session callback
	GameSessCallback(ctx context.Context, in *GameSessCallbackReq, opts ...grpc.CallOption) (*GameSessCallbackResp, error)
	// 淘汰赛 callback
	PvpKnockoutSettle(ctx context.Context, in *PvpKnockoutSettleReq, opts ...grpc.CallOption) (*PvpKnockoutSettleResp, error)
	// pve 在同一 battleId 中进入下一关
	GamePveNext(ctx context.Context, in *GamePveNextReq, opts ...grpc.CallOption) (*GamePveNextResp, error)
}

type gameInteractionSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewGameInteractionSvcClient(cc grpc.ClientConnInterface) GameInteractionSvcClient {
	return &gameInteractionSvcClient{cc}
}

func (c *gameInteractionSvcClient) ConsumeEnergy(ctx context.Context, in *ConsumeEnergyReq, opts ...grpc.CallOption) (*ConsumeEnergyResp, error) {
	out := new(ConsumeEnergyResp)
	err := c.cc.Invoke(ctx, GameInteractionSvc_ConsumeEnergy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameInteractionSvcClient) GameCallback(ctx context.Context, in *GameCallbackReq, opts ...grpc.CallOption) (*GameCallbackResp, error) {
	out := new(GameCallbackResp)
	err := c.cc.Invoke(ctx, GameInteractionSvc_GameCallback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameInteractionSvcClient) GameSessCallback(ctx context.Context, in *GameSessCallbackReq, opts ...grpc.CallOption) (*GameSessCallbackResp, error) {
	out := new(GameSessCallbackResp)
	err := c.cc.Invoke(ctx, GameInteractionSvc_GameSessCallback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameInteractionSvcClient) PvpKnockoutSettle(ctx context.Context, in *PvpKnockoutSettleReq, opts ...grpc.CallOption) (*PvpKnockoutSettleResp, error) {
	out := new(PvpKnockoutSettleResp)
	err := c.cc.Invoke(ctx, GameInteractionSvc_PvpKnockoutSettle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameInteractionSvcClient) GamePveNext(ctx context.Context, in *GamePveNextReq, opts ...grpc.CallOption) (*GamePveNextResp, error) {
	out := new(GamePveNextResp)
	err := c.cc.Invoke(ctx, GameInteractionSvc_GamePveNext_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameInteractionSvcServer is the server API for GameInteractionSvc service.
// All implementations must embed UnimplementedGameInteractionSvcServer
// for forward compatibility
type GameInteractionSvcServer interface {
	// 消耗体力值
	ConsumeEnergy(context.Context, *ConsumeEnergyReq) (*ConsumeEnergyResp, error)
	// game over callback
	GameCallback(context.Context, *GameCallbackReq) (*GameCallbackResp, error)
	// game session callback
	GameSessCallback(context.Context, *GameSessCallbackReq) (*GameSessCallbackResp, error)
	// 淘汰赛 callback
	PvpKnockoutSettle(context.Context, *PvpKnockoutSettleReq) (*PvpKnockoutSettleResp, error)
	// pve 在同一 battleId 中进入下一关
	GamePveNext(context.Context, *GamePveNextReq) (*GamePveNextResp, error)
	mustEmbedUnimplementedGameInteractionSvcServer()
}

// UnimplementedGameInteractionSvcServer must be embedded to have forward compatible implementations.
type UnimplementedGameInteractionSvcServer struct {
}

func (UnimplementedGameInteractionSvcServer) ConsumeEnergy(context.Context, *ConsumeEnergyReq) (*ConsumeEnergyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumeEnergy not implemented")
}
func (UnimplementedGameInteractionSvcServer) GameCallback(context.Context, *GameCallbackReq) (*GameCallbackResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameCallback not implemented")
}
func (UnimplementedGameInteractionSvcServer) GameSessCallback(context.Context, *GameSessCallbackReq) (*GameSessCallbackResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameSessCallback not implemented")
}
func (UnimplementedGameInteractionSvcServer) PvpKnockoutSettle(context.Context, *PvpKnockoutSettleReq) (*PvpKnockoutSettleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PvpKnockoutSettle not implemented")
}
func (UnimplementedGameInteractionSvcServer) GamePveNext(context.Context, *GamePveNextReq) (*GamePveNextResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GamePveNext not implemented")
}
func (UnimplementedGameInteractionSvcServer) mustEmbedUnimplementedGameInteractionSvcServer() {}

// UnsafeGameInteractionSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameInteractionSvcServer will
// result in compilation errors.
type UnsafeGameInteractionSvcServer interface {
	mustEmbedUnimplementedGameInteractionSvcServer()
}

func RegisterGameInteractionSvcServer(s grpc.ServiceRegistrar, srv GameInteractionSvcServer) {
	s.RegisterService(&GameInteractionSvc_ServiceDesc, srv)
}

func _GameInteractionSvc_ConsumeEnergy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeEnergyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameInteractionSvcServer).ConsumeEnergy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameInteractionSvc_ConsumeEnergy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameInteractionSvcServer).ConsumeEnergy(ctx, req.(*ConsumeEnergyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameInteractionSvc_GameCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameInteractionSvcServer).GameCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameInteractionSvc_GameCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameInteractionSvcServer).GameCallback(ctx, req.(*GameCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameInteractionSvc_GameSessCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameSessCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameInteractionSvcServer).GameSessCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameInteractionSvc_GameSessCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameInteractionSvcServer).GameSessCallback(ctx, req.(*GameSessCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameInteractionSvc_PvpKnockoutSettle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PvpKnockoutSettleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameInteractionSvcServer).PvpKnockoutSettle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameInteractionSvc_PvpKnockoutSettle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameInteractionSvcServer).PvpKnockoutSettle(ctx, req.(*PvpKnockoutSettleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameInteractionSvc_GamePveNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GamePveNextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameInteractionSvcServer).GamePveNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameInteractionSvc_GamePveNext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameInteractionSvcServer).GamePveNext(ctx, req.(*GamePveNextReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameInteractionSvc_ServiceDesc is the grpc.ServiceDesc for GameInteractionSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameInteractionSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GameInteractionSvc",
	HandlerType: (*GameInteractionSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsumeEnergy",
			Handler:    _GameInteractionSvc_ConsumeEnergy_Handler,
		},
		{
			MethodName: "GameCallback",
			Handler:    _GameInteractionSvc_GameCallback_Handler,
		},
		{
			MethodName: "GameSessCallback",
			Handler:    _GameInteractionSvc_GameSessCallback_Handler,
		},
		{
			MethodName: "PvpKnockoutSettle",
			Handler:    _GameInteractionSvc_PvpKnockoutSettle_Handler,
		},
		{
			MethodName: "GamePveNext",
			Handler:    _GameInteractionSvc_GamePveNext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_interaction.proto",
}
