// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: platform.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PropTradeSvc_ConsumeProp_FullMethodName      = "/PropTradeSvc/ConsumeProp"
	PropTradeSvc_QueryProp_FullMethodName        = "/PropTradeSvc/QueryProp"
	PropTradeSvc_AddProp_FullMethodName          = "/PropTradeSvc/AddProp"
	PropTradeSvc_QueryOrderStatus_FullMethodName = "/PropTradeSvc/QueryOrderStatus"
	PropTradeSvc_CreateOneGoods_FullMethodName   = "/PropTradeSvc/CreateOneGoods"
	PropTradeSvc_VerifyPayOrder_FullMethodName   = "/PropTradeSvc/VerifyPayOrder"
	PropTradeSvc_OrderDeliver_FullMethodName     = "/PropTradeSvc/OrderDeliver"
)

// PropTradeSvcClient is the client API for PropTradeSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropTradeSvcClient interface {
	// 游戏调用平台，消费“通用道具”
	ConsumeProp(ctx context.Context, in *ConsumePropReq, opts ...grpc.CallOption) (*ConsumePropResp, error)
	// 查询游戏道具
	QueryProp(ctx context.Context, in *QueryPropReq, opts ...grpc.CallOption) (*QueryPropResp, error)
	// 给玩家增加道具
	AddProp(ctx context.Context, in *AddPropReq, opts ...grpc.CallOption) (*AddPropResp, error)
	// 查询订单状态
	QueryOrderStatus(ctx context.Context, in *QueryOrderStatusReq, opts ...grpc.CallOption) (*QueryOrderStatusResp, error)
	// 创建一个新的礼包商品
	CreateOneGoods(ctx context.Context, in *CreateOneGoodsReq, opts ...grpc.CallOption) (*CreateOneGoodsResp, error)
	// 订单校验。用于验证法币支付的订单
	VerifyPayOrder(ctx context.Context, in *VerifyPayOrderReq, opts ...grpc.CallOption) (*VerifyPayOrderResp, error)
	// 针对法币支付的订单的发货/交付
	OrderDeliver(ctx context.Context, in *OrderDeliverReq, opts ...grpc.CallOption) (*OrderDeliverResp, error)
}

type propTradeSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewPropTradeSvcClient(cc grpc.ClientConnInterface) PropTradeSvcClient {
	return &propTradeSvcClient{cc}
}

func (c *propTradeSvcClient) ConsumeProp(ctx context.Context, in *ConsumePropReq, opts ...grpc.CallOption) (*ConsumePropResp, error) {
	out := new(ConsumePropResp)
	err := c.cc.Invoke(ctx, PropTradeSvc_ConsumeProp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propTradeSvcClient) QueryProp(ctx context.Context, in *QueryPropReq, opts ...grpc.CallOption) (*QueryPropResp, error) {
	out := new(QueryPropResp)
	err := c.cc.Invoke(ctx, PropTradeSvc_QueryProp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propTradeSvcClient) AddProp(ctx context.Context, in *AddPropReq, opts ...grpc.CallOption) (*AddPropResp, error) {
	out := new(AddPropResp)
	err := c.cc.Invoke(ctx, PropTradeSvc_AddProp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propTradeSvcClient) QueryOrderStatus(ctx context.Context, in *QueryOrderStatusReq, opts ...grpc.CallOption) (*QueryOrderStatusResp, error) {
	out := new(QueryOrderStatusResp)
	err := c.cc.Invoke(ctx, PropTradeSvc_QueryOrderStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propTradeSvcClient) CreateOneGoods(ctx context.Context, in *CreateOneGoodsReq, opts ...grpc.CallOption) (*CreateOneGoodsResp, error) {
	out := new(CreateOneGoodsResp)
	err := c.cc.Invoke(ctx, PropTradeSvc_CreateOneGoods_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propTradeSvcClient) VerifyPayOrder(ctx context.Context, in *VerifyPayOrderReq, opts ...grpc.CallOption) (*VerifyPayOrderResp, error) {
	out := new(VerifyPayOrderResp)
	err := c.cc.Invoke(ctx, PropTradeSvc_VerifyPayOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propTradeSvcClient) OrderDeliver(ctx context.Context, in *OrderDeliverReq, opts ...grpc.CallOption) (*OrderDeliverResp, error) {
	out := new(OrderDeliverResp)
	err := c.cc.Invoke(ctx, PropTradeSvc_OrderDeliver_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropTradeSvcServer is the server API for PropTradeSvc service.
// All implementations must embed UnimplementedPropTradeSvcServer
// for forward compatibility
type PropTradeSvcServer interface {
	// 游戏调用平台，消费“通用道具”
	ConsumeProp(context.Context, *ConsumePropReq) (*ConsumePropResp, error)
	// 查询游戏道具
	QueryProp(context.Context, *QueryPropReq) (*QueryPropResp, error)
	// 给玩家增加道具
	AddProp(context.Context, *AddPropReq) (*AddPropResp, error)
	// 查询订单状态
	QueryOrderStatus(context.Context, *QueryOrderStatusReq) (*QueryOrderStatusResp, error)
	// 创建一个新的礼包商品
	CreateOneGoods(context.Context, *CreateOneGoodsReq) (*CreateOneGoodsResp, error)
	// 订单校验。用于验证法币支付的订单
	VerifyPayOrder(context.Context, *VerifyPayOrderReq) (*VerifyPayOrderResp, error)
	// 针对法币支付的订单的发货/交付
	OrderDeliver(context.Context, *OrderDeliverReq) (*OrderDeliverResp, error)
	mustEmbedUnimplementedPropTradeSvcServer()
}

// UnimplementedPropTradeSvcServer must be embedded to have forward compatible implementations.
type UnimplementedPropTradeSvcServer struct {
}

func (UnimplementedPropTradeSvcServer) ConsumeProp(context.Context, *ConsumePropReq) (*ConsumePropResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumeProp not implemented")
}
func (UnimplementedPropTradeSvcServer) QueryProp(context.Context, *QueryPropReq) (*QueryPropResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryProp not implemented")
}
func (UnimplementedPropTradeSvcServer) AddProp(context.Context, *AddPropReq) (*AddPropResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProp not implemented")
}
func (UnimplementedPropTradeSvcServer) QueryOrderStatus(context.Context, *QueryOrderStatusReq) (*QueryOrderStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrderStatus not implemented")
}
func (UnimplementedPropTradeSvcServer) CreateOneGoods(context.Context, *CreateOneGoodsReq) (*CreateOneGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOneGoods not implemented")
}
func (UnimplementedPropTradeSvcServer) VerifyPayOrder(context.Context, *VerifyPayOrderReq) (*VerifyPayOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPayOrder not implemented")
}
func (UnimplementedPropTradeSvcServer) OrderDeliver(context.Context, *OrderDeliverReq) (*OrderDeliverResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderDeliver not implemented")
}
func (UnimplementedPropTradeSvcServer) mustEmbedUnimplementedPropTradeSvcServer() {}

// UnsafePropTradeSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropTradeSvcServer will
// result in compilation errors.
type UnsafePropTradeSvcServer interface {
	mustEmbedUnimplementedPropTradeSvcServer()
}

func RegisterPropTradeSvcServer(s grpc.ServiceRegistrar, srv PropTradeSvcServer) {
	s.RegisterService(&PropTradeSvc_ServiceDesc, srv)
}

func _PropTradeSvc_ConsumeProp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumePropReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropTradeSvcServer).ConsumeProp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropTradeSvc_ConsumeProp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropTradeSvcServer).ConsumeProp(ctx, req.(*ConsumePropReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropTradeSvc_QueryProp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPropReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropTradeSvcServer).QueryProp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropTradeSvc_QueryProp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropTradeSvcServer).QueryProp(ctx, req.(*QueryPropReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropTradeSvc_AddProp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPropReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropTradeSvcServer).AddProp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropTradeSvc_AddProp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropTradeSvcServer).AddProp(ctx, req.(*AddPropReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropTradeSvc_QueryOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOrderStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropTradeSvcServer).QueryOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropTradeSvc_QueryOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropTradeSvcServer).QueryOrderStatus(ctx, req.(*QueryOrderStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropTradeSvc_CreateOneGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOneGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropTradeSvcServer).CreateOneGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropTradeSvc_CreateOneGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropTradeSvcServer).CreateOneGoods(ctx, req.(*CreateOneGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropTradeSvc_VerifyPayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPayOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropTradeSvcServer).VerifyPayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropTradeSvc_VerifyPayOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropTradeSvcServer).VerifyPayOrder(ctx, req.(*VerifyPayOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropTradeSvc_OrderDeliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderDeliverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropTradeSvcServer).OrderDeliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PropTradeSvc_OrderDeliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropTradeSvcServer).OrderDeliver(ctx, req.(*OrderDeliverReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PropTradeSvc_ServiceDesc is the grpc.ServiceDesc for PropTradeSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropTradeSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PropTradeSvc",
	HandlerType: (*PropTradeSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsumeProp",
			Handler:    _PropTradeSvc_ConsumeProp_Handler,
		},
		{
			MethodName: "QueryProp",
			Handler:    _PropTradeSvc_QueryProp_Handler,
		},
		{
			MethodName: "AddProp",
			Handler:    _PropTradeSvc_AddProp_Handler,
		},
		{
			MethodName: "QueryOrderStatus",
			Handler:    _PropTradeSvc_QueryOrderStatus_Handler,
		},
		{
			MethodName: "CreateOneGoods",
			Handler:    _PropTradeSvc_CreateOneGoods_Handler,
		},
		{
			MethodName: "VerifyPayOrder",
			Handler:    _PropTradeSvc_VerifyPayOrder_Handler,
		},
		{
			MethodName: "OrderDeliver",
			Handler:    _PropTradeSvc_OrderDeliver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform.proto",
}
