// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: platform.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单状态，平台可根据订单需求，进行增减
type OrderStatus int32

const (
	// 查不到此订单
	OrderStatus_OrderEmpty_Status OrderStatus = 0
	// 支付中
	OrderStatus_OrderCreate OrderStatus = 1
	// 支付成功
	OrderStatus_OrderPaySuccess OrderStatus = 2
	// 支付失败
	OrderStatus_OrderPayFailed OrderStatus = 3
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "OrderEmpty_Status",
		1: "OrderCreate",
		2: "OrderPaySuccess",
		3: "OrderPayFailed",
	}
	OrderStatus_value = map[string]int32{
		"OrderEmpty_Status": 0,
		"OrderCreate":       1,
		"OrderPaySuccess":   2,
		"OrderPayFailed":    3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_platform_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{0}
}

type ConsumePropReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 使用道具的玩家 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
	// 使用道具的类型 | @inject_tag: msgpack:"propId" json:"propId"
	PropId int64 `protobuf:"varint,3,opt,name=propId,proto3" json:"propId" msgpack:"propId"`
	// 使用道具的数量 | @inject_tag: msgpack:"num" json:"num"
	Num int32 `protobuf:"varint,4,opt,name=num,proto3" json:"num" msgpack:"num"`
	// 所在对局 | @inject_tag: msgpack:"battleId" json:"battleId"
	BattleId int64 `protobuf:"varint,5,opt,name=battleId,proto3" json:"battleId" msgpack:"battleId"`
}

func (x *ConsumePropReq) Reset() {
	*x = ConsumePropReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumePropReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumePropReq) ProtoMessage() {}

func (x *ConsumePropReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumePropReq.ProtoReflect.Descriptor instead.
func (*ConsumePropReq) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumePropReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *ConsumePropReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ConsumePropReq) GetPropId() int64 {
	if x != nil {
		return x.PropId
	}
	return 0
}

func (x *ConsumePropReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ConsumePropReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

type ConsumePropResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 使用后，该道具的剩余数量 | @inject_tag: msgpack:"resNum" json:"resNum"
	ResNum int32 `protobuf:"varint,2,opt,name=resNum,proto3" json:"resNum" msgpack:"resNum"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message" msgpack:"message"`
}

func (x *ConsumePropResp) Reset() {
	*x = ConsumePropResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumePropResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumePropResp) ProtoMessage() {}

func (x *ConsumePropResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumePropResp.ProtoReflect.Descriptor instead.
func (*ConsumePropResp) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumePropResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConsumePropResp) GetResNum() int32 {
	if x != nil {
		return x.ResNum
	}
	return 0
}

func (x *ConsumePropResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryPropReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏 id，游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 玩家 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
}

func (x *QueryPropReq) Reset() {
	*x = QueryPropReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPropReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPropReq) ProtoMessage() {}

func (x *QueryPropReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPropReq.ProtoReflect.Descriptor instead.
func (*QueryPropReq) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{2}
}

func (x *QueryPropReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *QueryPropReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type QueryPropResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 道具的数量信息 | @inject_tag: msgpack:"propInfo" json:"propInfo"
	PropInfo map[int64]int32 `protobuf:"bytes,3,rep,name=propInfo,proto3" json:"propInfo" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" msgpack:"propInfo"`
}

func (x *QueryPropResp) Reset() {
	*x = QueryPropResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPropResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPropResp) ProtoMessage() {}

func (x *QueryPropResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPropResp.ProtoReflect.Descriptor instead.
func (*QueryPropResp) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPropResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryPropResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QueryPropResp) GetPropInfo() map[int64]int32 {
	if x != nil {
		return x.PropInfo
	}
	return nil
}

type QueryOrderStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 查询的订单号 | @inject_tag: msgpack:"orderNum" json:"orderNum"
	OrderNum string `protobuf:"bytes,2,opt,name=orderNum,proto3" json:"orderNum" msgpack:"orderNum"`
}

func (x *QueryOrderStatusReq) Reset() {
	*x = QueryOrderStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrderStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderStatusReq) ProtoMessage() {}

func (x *QueryOrderStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderStatusReq.ProtoReflect.Descriptor instead.
func (*QueryOrderStatusReq) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{4}
}

func (x *QueryOrderStatusReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *QueryOrderStatusReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type QueryOrderStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 订单状态 | @inject_tag: msgpack:"status" json:"status"
	Status OrderStatus `protobuf:"varint,3,opt,name=status,proto3,enum=OrderStatus" json:"status" msgpack:"status"`
}

func (x *QueryOrderStatusResp) Reset() {
	*x = QueryOrderStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrderStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderStatusResp) ProtoMessage() {}

func (x *QueryOrderStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderStatusResp.ProtoReflect.Descriptor instead.
func (*QueryOrderStatusResp) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{5}
}

func (x *QueryOrderStatusResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryOrderStatusResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QueryOrderStatusResp) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_OrderEmpty_Status
}

type CreateOneGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 礼包价位 | @inject_tag: msgpack:"price" json:"price"
	Price float32 `protobuf:"fixed32,1,opt,name=price,proto3" json:"price" msgpack:"price"`
	// 礼包商品标识，like:`{"props": {"1": 5, "2": 5, "3": 1, "10001": 1}}` | @inject_tag: msgpack:"goodsDetail" json:"goodsDetail"
	GoodsDetail string `protobuf:"bytes,2,opt,name=goodsDetail,proto3" json:"goodsDetail" msgpack:"goodsDetail"`
}

func (x *CreateOneGoodsReq) Reset() {
	*x = CreateOneGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOneGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOneGoodsReq) ProtoMessage() {}

func (x *CreateOneGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOneGoodsReq.ProtoReflect.Descriptor instead.
func (*CreateOneGoodsReq) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOneGoodsReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOneGoodsReq) GetGoodsDetail() string {
	if x != nil {
		return x.GoodsDetail
	}
	return ""
}

type CreateOneGoodsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 礼包商品的 id | @inject_tag: msgpack:"skuId" json:"skuId"
	SkuId string `protobuf:"bytes,3,opt,name=skuId,proto3" json:"skuId" msgpack:"skuId"`
}

func (x *CreateOneGoodsResp) Reset() {
	*x = CreateOneGoodsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOneGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOneGoodsResp) ProtoMessage() {}

func (x *CreateOneGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOneGoodsResp.ProtoReflect.Descriptor instead.
func (*CreateOneGoodsResp) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOneGoodsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateOneGoodsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateOneGoodsResp) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

type AddPropReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 增加的道具信息 | @inject_tag: msgpack:"addMap" json:"addMap"
	AddMap map[int64]int32 `protobuf:"bytes,2,rep,name=addMap,proto3" json:"addMap" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" msgpack:"addMap"`
	// 玩家 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
}

func (x *AddPropReq) Reset() {
	*x = AddPropReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPropReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPropReq) ProtoMessage() {}

func (x *AddPropReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPropReq.ProtoReflect.Descriptor instead.
func (*AddPropReq) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{8}
}

func (x *AddPropReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *AddPropReq) GetAddMap() map[int64]int32 {
	if x != nil {
		return x.AddMap
	}
	return nil
}

func (x *AddPropReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type AddPropResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 道具信息 | @inject_tag: msgpack:"propInfo" json:"propInfo"
	PropInfo map[int64]int32 `protobuf:"bytes,3,rep,name=propInfo,proto3" json:"propInfo" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" msgpack:"propInfo"`
}

func (x *AddPropResp) Reset() {
	*x = AddPropResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPropResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPropResp) ProtoMessage() {}

func (x *AddPropResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPropResp.ProtoReflect.Descriptor instead.
func (*AddPropResp) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{9}
}

func (x *AddPropResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddPropResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddPropResp) GetPropInfo() map[int64]int32 {
	if x != nil {
		return x.PropInfo
	}
	return nil
}

type VerifyPayOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 使用道具的玩家 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
	// 订单标识 | @inject_tag: msgpack:"orderNum" json:"orderNum"
	OrderNum string `protobuf:"bytes,3,opt,name=orderNum,proto3" json:"orderNum" msgpack:"orderNum"`
}

func (x *VerifyPayOrderReq) Reset() {
	*x = VerifyPayOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyPayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPayOrderReq) ProtoMessage() {}

func (x *VerifyPayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPayOrderReq.ProtoReflect.Descriptor instead.
func (*VerifyPayOrderReq) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyPayOrderReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *VerifyPayOrderReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *VerifyPayOrderReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type VerifyPayOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
}

func (x *VerifyPayOrderResp) Reset() {
	*x = VerifyPayOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyPayOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPayOrderResp) ProtoMessage() {}

func (x *VerifyPayOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPayOrderResp.ProtoReflect.Descriptor instead.
func (*VerifyPayOrderResp) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyPayOrderResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VerifyPayOrderResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OrderDeliverReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 使用道具的玩家 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
	// 订单标识 | @inject_tag: msgpack:"orderNum" json:"orderNum"
	OrderNum string `protobuf:"bytes,3,opt,name=orderNum,proto3" json:"orderNum" msgpack:"orderNum"`
}

func (x *OrderDeliverReq) Reset() {
	*x = OrderDeliverReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDeliverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeliverReq) ProtoMessage() {}

func (x *OrderDeliverReq) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeliverReq.ProtoReflect.Descriptor instead.
func (*OrderDeliverReq) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{12}
}

func (x *OrderDeliverReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *OrderDeliverReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *OrderDeliverReq) GetOrderNum() string {
	if x != nil {
		return x.OrderNum
	}
	return ""
}

type OrderDeliverResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
}

func (x *OrderDeliverResp) Reset() {
	*x = OrderDeliverResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_platform_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDeliverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeliverResp) ProtoMessage() {}

func (x *OrderDeliverResp) ProtoReflect() protoreflect.Message {
	mi := &file_platform_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeliverResp.ProtoReflect.Descriptor instead.
func (*OrderDeliverResp) Descriptor() ([]byte, []int) {
	return file_platform_proto_rawDescGZIP(), []int{13}
}

func (x *OrderDeliverResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderDeliverResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_platform_proto protoreflect.FileDescriptor

var file_platform_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x80, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x70,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70,
	0x72, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x72,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x4e,
	0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x38, 0x0a, 0x0c,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x38,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3b, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x49, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d,
	0x22, 0x62, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x24,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x4b, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x6e,
	0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x22, 0x50, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x6b, 0x75, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6b,
	0x75, 0x49, 0x64, 0x22, 0xa2, 0x01, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x61, 0x64,
	0x64, 0x4d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x41, 0x64, 0x64,
	0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x61, 0x64, 0x64, 0x4d, 0x61, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x1a, 0x39, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa8, 0x01, 0x0a, 0x0b, 0x41, 0x64, 0x64,
	0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x36,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3b, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x59, 0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x61, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x3a,
	0x0a, 0x12, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x57, 0x0a, 0x0f, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x22, 0x38, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x5e, 0x0a,
	0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x11,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x50, 0x61, 0x79, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x32, 0x8c, 0x03,
	0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x70, 0x54, 0x72, 0x61, 0x64, 0x65, 0x53, 0x76, 0x63, 0x12, 0x32,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x0f, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x2c, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x12,
	0x0d, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0e,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x26, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x0b, 0x2e, 0x41, 0x64,
	0x64, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x72,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x12, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x6e, 0x65, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x64, 0x5a, 0x62,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x68, 0x61, 0x6e,
	0x79, 0x75, 0x6a, 0x69, 0x65, 0x2f, 0x67, 0x6f, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2f, 0x70, 0x62, 0x5f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_platform_proto_rawDescOnce sync.Once
	file_platform_proto_rawDescData = file_platform_proto_rawDesc
)

func file_platform_proto_rawDescGZIP() []byte {
	file_platform_proto_rawDescOnce.Do(func() {
		file_platform_proto_rawDescData = protoimpl.X.CompressGZIP(file_platform_proto_rawDescData)
	})
	return file_platform_proto_rawDescData
}

var file_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_platform_proto_goTypes = []interface{}{
	(OrderStatus)(0),             // 0: OrderStatus
	(*ConsumePropReq)(nil),       // 1: ConsumePropReq
	(*ConsumePropResp)(nil),      // 2: ConsumePropResp
	(*QueryPropReq)(nil),         // 3: QueryPropReq
	(*QueryPropResp)(nil),        // 4: QueryPropResp
	(*QueryOrderStatusReq)(nil),  // 5: QueryOrderStatusReq
	(*QueryOrderStatusResp)(nil), // 6: QueryOrderStatusResp
	(*CreateOneGoodsReq)(nil),    // 7: CreateOneGoodsReq
	(*CreateOneGoodsResp)(nil),   // 8: CreateOneGoodsResp
	(*AddPropReq)(nil),           // 9: AddPropReq
	(*AddPropResp)(nil),          // 10: AddPropResp
	(*VerifyPayOrderReq)(nil),    // 11: VerifyPayOrderReq
	(*VerifyPayOrderResp)(nil),   // 12: VerifyPayOrderResp
	(*OrderDeliverReq)(nil),      // 13: OrderDeliverReq
	(*OrderDeliverResp)(nil),     // 14: OrderDeliverResp
	nil,                          // 15: QueryPropResp.PropInfoEntry
	nil,                          // 16: AddPropReq.AddMapEntry
	nil,                          // 17: AddPropResp.PropInfoEntry
}
var file_platform_proto_depIdxs = []int32{
	15, // 0: QueryPropResp.propInfo:type_name -> QueryPropResp.PropInfoEntry
	0,  // 1: QueryOrderStatusResp.status:type_name -> OrderStatus
	16, // 2: AddPropReq.addMap:type_name -> AddPropReq.AddMapEntry
	17, // 3: AddPropResp.propInfo:type_name -> AddPropResp.PropInfoEntry
	1,  // 4: PropTradeSvc.ConsumeProp:input_type -> ConsumePropReq
	3,  // 5: PropTradeSvc.QueryProp:input_type -> QueryPropReq
	9,  // 6: PropTradeSvc.AddProp:input_type -> AddPropReq
	5,  // 7: PropTradeSvc.QueryOrderStatus:input_type -> QueryOrderStatusReq
	7,  // 8: PropTradeSvc.CreateOneGoods:input_type -> CreateOneGoodsReq
	11, // 9: PropTradeSvc.VerifyPayOrder:input_type -> VerifyPayOrderReq
	13, // 10: PropTradeSvc.OrderDeliver:input_type -> OrderDeliverReq
	2,  // 11: PropTradeSvc.ConsumeProp:output_type -> ConsumePropResp
	4,  // 12: PropTradeSvc.QueryProp:output_type -> QueryPropResp
	10, // 13: PropTradeSvc.AddProp:output_type -> AddPropResp
	6,  // 14: PropTradeSvc.QueryOrderStatus:output_type -> QueryOrderStatusResp
	8,  // 15: PropTradeSvc.CreateOneGoods:output_type -> CreateOneGoodsResp
	12, // 16: PropTradeSvc.VerifyPayOrder:output_type -> VerifyPayOrderResp
	14, // 17: PropTradeSvc.OrderDeliver:output_type -> OrderDeliverResp
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_platform_proto_init() }
func file_platform_proto_init() {
	if File_platform_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_platform_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumePropReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumePropResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPropReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPropResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrderStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrderStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOneGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOneGoodsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPropReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPropResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyPayOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyPayOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDeliverReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_platform_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDeliverResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_platform_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platform_proto_goTypes,
		DependencyIndexes: file_platform_proto_depIdxs,
		EnumInfos:         file_platform_proto_enumTypes,
		MessageInfos:      file_platform_proto_msgTypes,
	}.Build()
	File_platform_proto = out.File
	file_platform_proto_rawDesc = nil
	file_platform_proto_goTypes = nil
	file_platform_proto_depIdxs = nil
}
