// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: player_task.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PlayerTaskSvc_QueryTasksState_FullMethodName = "/PlayerTaskSvc/QueryTasksState"
)

// PlayerTaskSvcClient is the client API for PlayerTaskSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerTaskSvcClient interface {
	// 游戏调用平台，获取一个玩家的一批任务的完成情况
	QueryTasksState(ctx context.Context, in *QueryTasksStateReq, opts ...grpc.CallOption) (*QueryTasksStateResp, error)
}

type playerTaskSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerTaskSvcClient(cc grpc.ClientConnInterface) PlayerTaskSvcClient {
	return &playerTaskSvcClient{cc}
}

func (c *playerTaskSvcClient) QueryTasksState(ctx context.Context, in *QueryTasksStateReq, opts ...grpc.CallOption) (*QueryTasksStateResp, error) {
	out := new(QueryTasksStateResp)
	err := c.cc.Invoke(ctx, PlayerTaskSvc_QueryTasksState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerTaskSvcServer is the server API for PlayerTaskSvc service.
// All implementations must embed UnimplementedPlayerTaskSvcServer
// for forward compatibility
type PlayerTaskSvcServer interface {
	// 游戏调用平台，获取一个玩家的一批任务的完成情况
	QueryTasksState(context.Context, *QueryTasksStateReq) (*QueryTasksStateResp, error)
	mustEmbedUnimplementedPlayerTaskSvcServer()
}

// UnimplementedPlayerTaskSvcServer must be embedded to have forward compatible implementations.
type UnimplementedPlayerTaskSvcServer struct {
}

func (UnimplementedPlayerTaskSvcServer) QueryTasksState(context.Context, *QueryTasksStateReq) (*QueryTasksStateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTasksState not implemented")
}
func (UnimplementedPlayerTaskSvcServer) mustEmbedUnimplementedPlayerTaskSvcServer() {}

// UnsafePlayerTaskSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerTaskSvcServer will
// result in compilation errors.
type UnsafePlayerTaskSvcServer interface {
	mustEmbedUnimplementedPlayerTaskSvcServer()
}

func RegisterPlayerTaskSvcServer(s grpc.ServiceRegistrar, srv PlayerTaskSvcServer) {
	s.RegisterService(&PlayerTaskSvc_ServiceDesc, srv)
}

func _PlayerTaskSvc_QueryTasksState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTasksStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerTaskSvcServer).QueryTasksState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerTaskSvc_QueryTasksState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerTaskSvcServer).QueryTasksState(ctx, req.(*QueryTasksStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerTaskSvc_ServiceDesc is the grpc.ServiceDesc for PlayerTaskSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerTaskSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PlayerTaskSvc",
	HandlerType: (*PlayerTaskSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryTasksState",
			Handler:    _PlayerTaskSvc_QueryTasksState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player_task.proto",
}
