// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: player_battle.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBestRecordOfFriendBattleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 关卡。忽略该条件传 -1。
	// 查询的是指定关卡下，时间最短 topN 的对战记录
	// | @inject_tag: msgpack:"levelId" json:"levelId"
	LevelId int32 `protobuf:"varint,2,opt,name=levelId,proto3" json:"levelId" msgpack:"levelId"`
	// 难度。特殊的筛选条件。忽略该条件传 0
	// 指定难度下，玩家最佳成绩 | @inject_tag: msgpack:"difficulty" json:"difficulty"
	Difficulty int32 `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty" msgpack:"difficulty"`
	// 玩家的 uid 列表，查询这些玩家的最高成绩的对战记录 | @inject_tag: msgpack:"uidList" json:"uidList"
	UidList []*UidWrapper `protobuf:"bytes,4,rep,name=uidList,proto3" json:"uidList" msgpack:"uidList"`
}

func (x *GetBestRecordOfFriendBattleReq) Reset() {
	*x = GetBestRecordOfFriendBattleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBestRecordOfFriendBattleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestRecordOfFriendBattleReq) ProtoMessage() {}

func (x *GetBestRecordOfFriendBattleReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestRecordOfFriendBattleReq.ProtoReflect.Descriptor instead.
func (*GetBestRecordOfFriendBattleReq) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{0}
}

func (x *GetBestRecordOfFriendBattleReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetBestRecordOfFriendBattleReq) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *GetBestRecordOfFriendBattleReq) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *GetBestRecordOfFriendBattleReq) GetUidList() []*UidWrapper {
	if x != nil {
		return x.UidList
	}
	return nil
}

type UidWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 玩家的 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
}

func (x *UidWrapper) Reset() {
	*x = UidWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UidWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UidWrapper) ProtoMessage() {}

func (x *UidWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UidWrapper.ProtoReflect.Descriptor instead.
func (*UidWrapper) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{1}
}

func (x *UidWrapper) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type NftIdWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 角色对应的 nftId | @inject_tag: msgpack:"nftId" json:"nftId"
	NftId int32 `protobuf:"varint,1,opt,name=nftId,proto3" json:"nftId" msgpack:"nftId"`
}

func (x *NftIdWrapper) Reset() {
	*x = NftIdWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NftIdWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NftIdWrapper) ProtoMessage() {}

func (x *NftIdWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NftIdWrapper.ProtoReflect.Descriptor instead.
func (*NftIdWrapper) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{2}
}

func (x *NftIdWrapper) GetNftId() int32 {
	if x != nil {
		return x.NftId
	}
	return 0
}

type GetBestRecordOfFriendBattleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 异常时错误信息 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 好友对战记录列表 | @inject_tag: msgpack:"list" json:"list"
	List []*BattleRecordOfFriend `protobuf:"bytes,3,rep,name=list,proto3" json:"list" msgpack:"list"`
}

func (x *GetBestRecordOfFriendBattleResp) Reset() {
	*x = GetBestRecordOfFriendBattleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBestRecordOfFriendBattleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestRecordOfFriendBattleResp) ProtoMessage() {}

func (x *GetBestRecordOfFriendBattleResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestRecordOfFriendBattleResp.ProtoReflect.Descriptor instead.
func (*GetBestRecordOfFriendBattleResp) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{3}
}

func (x *GetBestRecordOfFriendBattleResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetBestRecordOfFriendBattleResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetBestRecordOfFriendBattleResp) GetList() []*BattleRecordOfFriend {
	if x != nil {
		return x.List
	}
	return nil
}

type BattleRecordOfFriend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 玩家 id | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
	// 玩家所使用的 nftId | @inject_tag: msgpack:"nftId" json:"nftId"
	NftId int32 `protobuf:"varint,2,opt,name=nftId,proto3" json:"nftId" msgpack:"nftId"`
	// 对局成绩，关卡id/分数/距离 | @inject_tag: msgpack:"grade" json:"grade"
	Grade string `protobuf:"bytes,3,opt,name=grade,proto3" json:"grade" msgpack:"grade"`
	// 对局时间的秒数 | @inject_tag: msgpack:"battleSec" json:"battleSec"
	BattleSec int32 `protobuf:"varint,4,opt,name=battleSec,proto3" json:"battleSec" msgpack:"battleSec"`
}

func (x *BattleRecordOfFriend) Reset() {
	*x = BattleRecordOfFriend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleRecordOfFriend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRecordOfFriend) ProtoMessage() {}

func (x *BattleRecordOfFriend) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRecordOfFriend.ProtoReflect.Descriptor instead.
func (*BattleRecordOfFriend) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{4}
}

func (x *BattleRecordOfFriend) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *BattleRecordOfFriend) GetNftId() int32 {
	if x != nil {
		return x.NftId
	}
	return 0
}

func (x *BattleRecordOfFriend) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *BattleRecordOfFriend) GetBattleSec() int32 {
	if x != nil {
		return x.BattleSec
	}
	return 0
}

type GetUserBattleInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户的 id | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
}

func (x *GetUserBattleInfoReq) Reset() {
	*x = GetUserBattleInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBattleInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBattleInfoReq) ProtoMessage() {}

func (x *GetUserBattleInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBattleInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserBattleInfoReq) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBattleInfoReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetUserBattleInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 异常时错误信息 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 当前对战的游戏，游戏的标识，如果没有，则为 0 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,3,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 当前对战的 battleId，如果没有则为 0 | @inject_tag: msgpack:"battleId" json:"battleId"
	BattleId int64 `protobuf:"varint,4,opt,name=battleId,proto3" json:"battleId" msgpack:"battleId"`
}

func (x *GetUserBattleInfoResp) Reset() {
	*x = GetUserBattleInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBattleInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBattleInfoResp) ProtoMessage() {}

func (x *GetUserBattleInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBattleInfoResp.ProtoReflect.Descriptor instead.
func (*GetUserBattleInfoResp) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserBattleInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserBattleInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserBattleInfoResp) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetUserBattleInfoResp) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

type GetNftTopNInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 关卡。忽略该条件传 -1。
	// 查询的是指定关卡下，通过关卡，且时间最短 topN 的对战记录
	// | @inject_tag: msgpack:"levelId" json:"levelId"
	LevelId int32 `protobuf:"varint,2,opt,name=levelId,proto3" json:"levelId" msgpack:"levelId"`
	// 难度。特殊的筛选条件,没有传0。
	// 指定难度下，玩家最佳成绩 | @inject_tag: msgpack:"difficulty" json:"difficulty"
	Difficulty int32 `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty" msgpack:"difficulty"`
	// 奖励类型(符文)，没有传-1
	// 指定奖励类型下的常用角色，和在这个阶段的占比（捕鱼） | @inject_tag: msgpack:"rewardType" json:"rewardType"
	RewardType int32 `protobuf:"varint,4,opt,name=rewardType,proto3" json:"rewardType" msgpack:"rewardType"`
	// 名次 | @inject_tag: msgpack:"rank" json:"rank"
	Rank int32 `protobuf:"varint,6,opt,name=rank,proto3" json:"rank" msgpack:"rank"`
	// 玩家成绩 | @inject_tag: msgpack:"score" json:"score"
	Score int32 `protobuf:"varint,7,opt,name=score,proto3" json:"score" msgpack:"score"`
}

func (x *GetNftTopNInfoReq) Reset() {
	*x = GetNftTopNInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNftTopNInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNftTopNInfoReq) ProtoMessage() {}

func (x *GetNftTopNInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNftTopNInfoReq.ProtoReflect.Descriptor instead.
func (*GetNftTopNInfoReq) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{7}
}

func (x *GetNftTopNInfoReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetNftTopNInfoReq) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *GetNftTopNInfoReq) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *GetNftTopNInfoReq) GetRewardType() int32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

func (x *GetNftTopNInfoReq) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GetNftTopNInfoReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetNftTopNInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 异常时错误信息 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// nft信息 | @inject_tag: msgpack:"nftList" json:"nftList"
	NftList []*NtfSimpleInfo `protobuf:"bytes,3,rep,name=nftList,proto3" json:"nftList" msgpack:"nftList"`
}

func (x *GetNftTopNInfoResp) Reset() {
	*x = GetNftTopNInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNftTopNInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNftTopNInfoResp) ProtoMessage() {}

func (x *GetNftTopNInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNftTopNInfoResp.ProtoReflect.Descriptor instead.
func (*GetNftTopNInfoResp) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{8}
}

func (x *GetNftTopNInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetNftTopNInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetNftTopNInfoResp) GetNftList() []*NtfSimpleInfo {
	if x != nil {
		return x.NftList
	}
	return nil
}

type NtfSimpleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// nftId | @inject_tag: msgpack:"nftId" json:"nftId"
	NftId int32 `protobuf:"varint,1,opt,name=nftId,proto3" json:"nftId" msgpack:"nftId"`
	// 使用率，百分比 | @inject_tag: msgpack:"rate" json:"rate"
	Rate int32 `protobuf:"varint,2,opt,name=rate,proto3" json:"rate" msgpack:"rate"`
}

func (x *NtfSimpleInfo) Reset() {
	*x = NtfSimpleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NtfSimpleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NtfSimpleInfo) ProtoMessage() {}

func (x *NtfSimpleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NtfSimpleInfo.ProtoReflect.Descriptor instead.
func (*NtfSimpleInfo) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{9}
}

func (x *NtfSimpleInfo) GetNftId() int32 {
	if x != nil {
		return x.NftId
	}
	return 0
}

func (x *NtfSimpleInfo) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type GetSurpassRateByScoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 关卡。忽略该条件传 -1。
	// 查询的是指定关卡下，时间最短 topN 的对战记录
	// | @inject_tag: msgpack:"levelId" json:"levelId"
	LevelId int32 `protobuf:"varint,2,opt,name=levelId,proto3" json:"levelId" msgpack:"levelId"`
	// 难度。特殊的筛选条件。
	// 指定难度下，玩家最佳成绩 | @inject_tag: msgpack:"difficulty" json:"difficulty"
	Difficulty int32 `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty" msgpack:"difficulty"`
	// 玩家成绩 | @inject_tag: msgpack:"score" json:"score"
	Score int32 `protobuf:"varint,4,opt,name=score,proto3" json:"score" msgpack:"score"`
}

func (x *GetSurpassRateByScoreReq) Reset() {
	*x = GetSurpassRateByScoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSurpassRateByScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurpassRateByScoreReq) ProtoMessage() {}

func (x *GetSurpassRateByScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurpassRateByScoreReq.ProtoReflect.Descriptor instead.
func (*GetSurpassRateByScoreReq) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{10}
}

func (x *GetSurpassRateByScoreReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetSurpassRateByScoreReq) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *GetSurpassRateByScoreReq) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *GetSurpassRateByScoreReq) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetSurpassRateByScoreResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 异常时错误信息 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 百分比 | @inject_tag: msgpack:"rate" json:"rate"
	Rate int32 `protobuf:"varint,3,opt,name=rate,proto3" json:"rate" msgpack:"rate"`
}

func (x *GetSurpassRateByScoreResp) Reset() {
	*x = GetSurpassRateByScoreResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSurpassRateByScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurpassRateByScoreResp) ProtoMessage() {}

func (x *GetSurpassRateByScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurpassRateByScoreResp.ProtoReflect.Descriptor instead.
func (*GetSurpassRateByScoreResp) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{11}
}

func (x *GetSurpassRateByScoreResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSurpassRateByScoreResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetSurpassRateByScoreResp) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type GetRuneRateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
}

func (x *GetRuneRateReq) Reset() {
	*x = GetRuneRateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRuneRateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuneRateReq) ProtoMessage() {}

func (x *GetRuneRateReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuneRateReq.ProtoReflect.Descriptor instead.
func (*GetRuneRateReq) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{12}
}

func (x *GetRuneRateReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type RuneRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 奖励符文类型，没获得符文-1 | @inject_tag: msgpack:"runeType" json:"runeType"
	RuneType int32 `protobuf:"varint,1,opt,name=runeType,proto3" json:"runeType" msgpack:"runeType"`
	// 获取占比 | @inject_tag: msgpack:"rate" json:"rate"
	Rate int32 `protobuf:"varint,2,opt,name=rate,proto3" json:"rate" msgpack:"rate"`
}

func (x *RuneRate) Reset() {
	*x = RuneRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuneRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuneRate) ProtoMessage() {}

func (x *RuneRate) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuneRate.ProtoReflect.Descriptor instead.
func (*RuneRate) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{13}
}

func (x *RuneRate) GetRuneType() int32 {
	if x != nil {
		return x.RuneType
	}
	return 0
}

func (x *RuneRate) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type GetRuneRateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 异常时错误信息 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 符文获取占比 | @inject_tag: msgpack:"runeRates" json:"runeRates"
	RuneRates []*RuneRate `protobuf:"bytes,3,rep,name=runeRates,proto3" json:"runeRates" msgpack:"runeRates"`
}

func (x *GetRuneRateResp) Reset() {
	*x = GetRuneRateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRuneRateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuneRateResp) ProtoMessage() {}

func (x *GetRuneRateResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuneRateResp.ProtoReflect.Descriptor instead.
func (*GetRuneRateResp) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{14}
}

func (x *GetRuneRateResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRuneRateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetRuneRateResp) GetRuneRates() []*RuneRate {
	if x != nil {
		return x.RuneRates
	}
	return nil
}

type GetDefeatNftTopNInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// nftID | @inject_tag: msgpack:"nftId" json:"nftId"
	NftId int32 `protobuf:"varint,2,opt,name=nftId,proto3" json:"nftId" msgpack:"nftId"`
	// 前几名 | @inject_tag: msgpack:"top" json:"top"
	Top int32 `protobuf:"varint,6,opt,name=top,proto3" json:"top" msgpack:"top"`
}

func (x *GetDefeatNftTopNInfoReq) Reset() {
	*x = GetDefeatNftTopNInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDefeatNftTopNInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefeatNftTopNInfoReq) ProtoMessage() {}

func (x *GetDefeatNftTopNInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefeatNftTopNInfoReq.ProtoReflect.Descriptor instead.
func (*GetDefeatNftTopNInfoReq) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{15}
}

func (x *GetDefeatNftTopNInfoReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetDefeatNftTopNInfoReq) GetNftId() int32 {
	if x != nil {
		return x.NftId
	}
	return 0
}

func (x *GetDefeatNftTopNInfoReq) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

type DefeatRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// nftID | @inject_tag: msgpack:"nftId" json:"nftId"
	NftId int32 `protobuf:"varint,1,opt,name=nftId,proto3" json:"nftId" msgpack:"nftId"`
	// 占比 | @inject_tag: msgpack:"rate" json:"rate"
	Rate int32 `protobuf:"varint,2,opt,name=rate,proto3" json:"rate" msgpack:"rate"`
	// 名次 | @inject_tag: msgpack:"rank" json:"rank"
	Rank int32 `protobuf:"varint,3,opt,name=rank,proto3" json:"rank" msgpack:"rank"`
}

func (x *DefeatRate) Reset() {
	*x = DefeatRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefeatRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefeatRate) ProtoMessage() {}

func (x *DefeatRate) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefeatRate.ProtoReflect.Descriptor instead.
func (*DefeatRate) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{16}
}

func (x *DefeatRate) GetNftId() int32 {
	if x != nil {
		return x.NftId
	}
	return 0
}

func (x *DefeatRate) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *DefeatRate) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GetDefeatNftTopNInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 异常时错误信息 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 战胜nft的nft信息 | @inject_tag: msgpack:"defeatRates" json:"defeatRates"
	DefeatRates []*DefeatRate `protobuf:"bytes,3,rep,name=defeatRates,proto3" json:"defeatRates" msgpack:"defeatRates"`
}

func (x *GetDefeatNftTopNInfoResp) Reset() {
	*x = GetDefeatNftTopNInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDefeatNftTopNInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefeatNftTopNInfoResp) ProtoMessage() {}

func (x *GetDefeatNftTopNInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefeatNftTopNInfoResp.ProtoReflect.Descriptor instead.
func (*GetDefeatNftTopNInfoResp) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{17}
}

func (x *GetDefeatNftTopNInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetDefeatNftTopNInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetDefeatNftTopNInfoResp) GetDefeatRates() []*DefeatRate {
	if x != nil {
		return x.DefeatRates
	}
	return nil
}

type GetInfoOfFriendHasUsingNftReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 指定的 uid 列表，这些 uid 是否使用过这些 nft | @inject_tag: msgpack:"uid" json:"uid"
	UidList []*UidWrapper `protobuf:"bytes,2,rep,name=uidList,proto3" json:"uid" msgpack:"uid"`
	// nftId 列表，好友(uid 对应的好友)是否用过这些 nft | @inject_tag: msgpack:"nftIdList" json:"nftIdList"
	NftIdList []*NftIdWrapper `protobuf:"bytes,3,rep,name=nftIdList,proto3" json:"nftIdList" msgpack:"nftIdList"`
}

func (x *GetInfoOfFriendHasUsingNftReq) Reset() {
	*x = GetInfoOfFriendHasUsingNftReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfoOfFriendHasUsingNftReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoOfFriendHasUsingNftReq) ProtoMessage() {}

func (x *GetInfoOfFriendHasUsingNftReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoOfFriendHasUsingNftReq.ProtoReflect.Descriptor instead.
func (*GetInfoOfFriendHasUsingNftReq) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{18}
}

func (x *GetInfoOfFriendHasUsingNftReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetInfoOfFriendHasUsingNftReq) GetUidList() []*UidWrapper {
	if x != nil {
		return x.UidList
	}
	return nil
}

func (x *GetInfoOfFriendHasUsingNftReq) GetNftIdList() []*NftIdWrapper {
	if x != nil {
		return x.NftIdList
	}
	return nil
}

type GetInfoOfFriendHasUsingNftResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 异常时错误信息 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 哪些 nft 被好友使用过。key:nftId, val:被哪些好友使用过 | @inject_tag: msgpack:"usingInfoMap" json:"usingInfoMap"
	UsingInfoMap map[int32]*FriendUidListOfUsingNft `protobuf:"bytes,3,rep,name=usingInfoMap,proto3" json:"usingInfoMap" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" msgpack:"usingInfoMap"`
}

func (x *GetInfoOfFriendHasUsingNftResp) Reset() {
	*x = GetInfoOfFriendHasUsingNftResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfoOfFriendHasUsingNftResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoOfFriendHasUsingNftResp) ProtoMessage() {}

func (x *GetInfoOfFriendHasUsingNftResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoOfFriendHasUsingNftResp.ProtoReflect.Descriptor instead.
func (*GetInfoOfFriendHasUsingNftResp) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{19}
}

func (x *GetInfoOfFriendHasUsingNftResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetInfoOfFriendHasUsingNftResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetInfoOfFriendHasUsingNftResp) GetUsingInfoMap() map[int32]*FriendUidListOfUsingNft {
	if x != nil {
		return x.UsingInfoMap
	}
	return nil
}

type FriendUidListOfUsingNft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 好友的 uid 列表 | @inject_tag: msgpack:"uidList" json:"uidList"
	UidList []*UidWrapper `protobuf:"bytes,1,rep,name=uidList,proto3" json:"uidList" msgpack:"uidList"`
}

func (x *FriendUidListOfUsingNft) Reset() {
	*x = FriendUidListOfUsingNft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendUidListOfUsingNft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendUidListOfUsingNft) ProtoMessage() {}

func (x *FriendUidListOfUsingNft) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendUidListOfUsingNft.ProtoReflect.Descriptor instead.
func (*FriendUidListOfUsingNft) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{20}
}

func (x *FriendUidListOfUsingNft) GetUidList() []*UidWrapper {
	if x != nil {
		return x.UidList
	}
	return nil
}

type GetNftUsingRateInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 指定的游戏，eg：角斗，跑酷 etc | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 指定的关卡 | @inject_tag: msgpack:"levelId" json:"levelId"
	LevelId int32 `protobuf:"varint,2,opt,name=levelId,proto3" json:"levelId" msgpack:"levelId"`
	// 指定的 nft id 列表 | @inject_tag: msgpack:"nftIdList" json:"nftIdList"
	NftIdList []*NftIdWrapper `protobuf:"bytes,3,rep,name=nftIdList,proto3" json:"nftIdList" msgpack:"nftIdList"`
}

func (x *GetNftUsingRateInfoReq) Reset() {
	*x = GetNftUsingRateInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNftUsingRateInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNftUsingRateInfoReq) ProtoMessage() {}

func (x *GetNftUsingRateInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNftUsingRateInfoReq.ProtoReflect.Descriptor instead.
func (*GetNftUsingRateInfoReq) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{21}
}

func (x *GetNftUsingRateInfoReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetNftUsingRateInfoReq) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *GetNftUsingRateInfoReq) GetNftIdList() []*NftIdWrapper {
	if x != nil {
		return x.NftIdList
	}
	return nil
}

type GetNftUsingRateInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 异常时错误信息 | @inject_tag: msgpack:"msg" json:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" msgpack:"msg"`
	// 指定的 nft 使用率信息 map | @inject_tag: msgpack:"nftUsingRateMap" json:"nftUsingRateMap"
	NftUsingRateMap map[int32]int32 `protobuf:"bytes,3,rep,name=nftUsingRateMap,proto3" json:"nftUsingRateMap" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3" msgpack:"nftUsingRateMap"`
}

func (x *GetNftUsingRateInfoResp) Reset() {
	*x = GetNftUsingRateInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_battle_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNftUsingRateInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNftUsingRateInfoResp) ProtoMessage() {}

func (x *GetNftUsingRateInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_battle_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNftUsingRateInfoResp.ProtoReflect.Descriptor instead.
func (*GetNftUsingRateInfoResp) Descriptor() ([]byte, []int) {
	return file_player_battle_proto_rawDescGZIP(), []int{22}
}

func (x *GetNftUsingRateInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetNftUsingRateInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetNftUsingRateInfoResp) GetNftUsingRateMap() map[int32]int32 {
	if x != nil {
		return x.NftUsingRateMap
	}
	return nil
}

var File_player_battle_proto protoreflect.FileDescriptor

var file_player_battle_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69,
	0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x07, 0x75, 0x69,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55, 0x69,
	0x64, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x07, 0x75, 0x69, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x1e, 0x0a, 0x0a, 0x55, 0x69, 0x64, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x22, 0x24, 0x0a, 0x0c, 0x4e, 0x66, 0x74, 0x49, 0x64, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x42, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x66, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x72, 0x0a, 0x14, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x66, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x65, 0x63, 0x22,
	0x28, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x22, 0xaf, 0x01, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63,
	0x75, 0x6c, 0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x64,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x07, 0x6e, 0x66,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4e, 0x74,
	0x66, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6e, 0x66, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x0d, 0x4e, 0x74, 0x66, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22,
	0x82, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x75, 0x72, 0x70, 0x61, 0x73, 0x73, 0x52, 0x61,
	0x74, 0x65, 0x42, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x22, 0x55, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x75, 0x72, 0x70, 0x61,
	0x73, 0x73, 0x52, 0x61, 0x74, 0x65, 0x42, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x28, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x52, 0x75, 0x6e, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x65, 0x52, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x75, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x75, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74,
	0x65, 0x22, 0x60, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6e, 0x65, 0x52, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x27, 0x0a, 0x09, 0x72, 0x75,
	0x6e, 0x65, 0x52, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x52, 0x75, 0x6e, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x65, 0x52, 0x61,
	0x74, 0x65, 0x73, 0x22, 0x59, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x65, 0x61, 0x74,
	0x4e, 0x66, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x6f, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x6f, 0x70, 0x22, 0x4a,
	0x0a, 0x0a, 0x44, 0x65, 0x66, 0x65, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x66, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x66, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x6f, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x66, 0x65, 0x61, 0x74, 0x4e, 0x66, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x0b,
	0x64, 0x65, 0x66, 0x65, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x65, 0x66, 0x65, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x0b,
	0x64, 0x65, 0x66, 0x65, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x48,
	0x61, 0x73, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x66, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x75, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55, 0x69, 0x64, 0x57, 0x72, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x52, 0x07, 0x75, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09,
	0x6e, 0x66, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x4e, 0x66, 0x74, 0x49, 0x64, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x09,
	0x6e, 0x66, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xf8, 0x01, 0x0a, 0x1e, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x48, 0x61, 0x73,
	0x55, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x55, 0x0a, 0x0c, 0x75, 0x73, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x4d,
	0x61, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x48, 0x61, 0x73, 0x55, 0x73, 0x69,
	0x6e, 0x67, 0x4e, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x75, 0x73, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x70, 0x1a, 0x59, 0x0a, 0x11, 0x55, 0x73, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x2e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x55, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x66, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x66, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x17, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x55, 0x69,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x66, 0x74, 0x12,
	0x25, 0x0a, 0x07, 0x75, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x55, 0x69, 0x64, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x07, 0x75,
	0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x77, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x74,
	0x55, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x49, 0x64, 0x12, 0x2b, 0x0a, 0x09, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4e, 0x66, 0x74, 0x49, 0x64, 0x57, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x52, 0x09, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0xdc, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x74, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x52,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x57, 0x0a, 0x0f, 0x6e, 0x66, 0x74, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x47, 0x65, 0x74,
	0x4e, 0x66, 0x74, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x2e, 0x4e, 0x66, 0x74, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x6e, 0x66, 0x74, 0x55, 0x73,
	0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x1a, 0x42, 0x0a, 0x14, 0x4e, 0x66,
	0x74, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xfa,
	0x04, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53,
	0x76, 0x63, 0x12, 0x44, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x16,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x42,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x4e, 0x66, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x2e, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x53, 0x75, 0x72, 0x70, 0x61, 0x73, 0x73, 0x52, 0x61, 0x74, 0x65, 0x42, 0x79, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x72, 0x70, 0x61, 0x73, 0x73, 0x52,
	0x61, 0x74, 0x65, 0x42, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x72, 0x70, 0x61, 0x73, 0x73, 0x52, 0x61, 0x74, 0x65, 0x42, 0x79,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x52, 0x75, 0x6e, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x75, 0x6e, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x75, 0x6e, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x4d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x65, 0x61, 0x74, 0x4e, 0x66, 0x74, 0x54,
	0x6f, 0x70, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66,
	0x65, 0x61, 0x74, 0x4e, 0x66, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x66, 0x65, 0x61, 0x74, 0x4e, 0x66, 0x74,
	0x54, 0x6f, 0x70, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x5f,
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x48, 0x61, 0x73, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x66, 0x74, 0x12, 0x1e, 0x2e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x48, 0x61,
	0x73, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x66, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x66, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x48, 0x61,
	0x73, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x4a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x74, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x74, 0x55,
	0x73, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x66, 0x74, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x64, 0x5a, 0x62, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x68, 0x61, 0x6e, 0x79,
	0x75, 0x6a, 0x69, 0x65, 0x2f, 0x67, 0x6f, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x2f, 0x70, 0x62, 0x5f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_player_battle_proto_rawDescOnce sync.Once
	file_player_battle_proto_rawDescData = file_player_battle_proto_rawDesc
)

func file_player_battle_proto_rawDescGZIP() []byte {
	file_player_battle_proto_rawDescOnce.Do(func() {
		file_player_battle_proto_rawDescData = protoimpl.X.CompressGZIP(file_player_battle_proto_rawDescData)
	})
	return file_player_battle_proto_rawDescData
}

var file_player_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_player_battle_proto_goTypes = []interface{}{
	(*GetBestRecordOfFriendBattleReq)(nil),  // 0: GetBestRecordOfFriendBattleReq
	(*UidWrapper)(nil),                      // 1: UidWrapper
	(*NftIdWrapper)(nil),                    // 2: NftIdWrapper
	(*GetBestRecordOfFriendBattleResp)(nil), // 3: GetBestRecordOfFriendBattleResp
	(*BattleRecordOfFriend)(nil),            // 4: BattleRecordOfFriend
	(*GetUserBattleInfoReq)(nil),            // 5: GetUserBattleInfoReq
	(*GetUserBattleInfoResp)(nil),           // 6: GetUserBattleInfoResp
	(*GetNftTopNInfoReq)(nil),               // 7: GetNftTopNInfoReq
	(*GetNftTopNInfoResp)(nil),              // 8: GetNftTopNInfoResp
	(*NtfSimpleInfo)(nil),                   // 9: NtfSimpleInfo
	(*GetSurpassRateByScoreReq)(nil),        // 10: GetSurpassRateByScoreReq
	(*GetSurpassRateByScoreResp)(nil),       // 11: GetSurpassRateByScoreResp
	(*GetRuneRateReq)(nil),                  // 12: GetRuneRateReq
	(*RuneRate)(nil),                        // 13: RuneRate
	(*GetRuneRateResp)(nil),                 // 14: GetRuneRateResp
	(*GetDefeatNftTopNInfoReq)(nil),         // 15: GetDefeatNftTopNInfoReq
	(*DefeatRate)(nil),                      // 16: DefeatRate
	(*GetDefeatNftTopNInfoResp)(nil),        // 17: GetDefeatNftTopNInfoResp
	(*GetInfoOfFriendHasUsingNftReq)(nil),   // 18: GetInfoOfFriendHasUsingNftReq
	(*GetInfoOfFriendHasUsingNftResp)(nil),  // 19: GetInfoOfFriendHasUsingNftResp
	(*FriendUidListOfUsingNft)(nil),         // 20: FriendUidListOfUsingNft
	(*GetNftUsingRateInfoReq)(nil),          // 21: GetNftUsingRateInfoReq
	(*GetNftUsingRateInfoResp)(nil),         // 22: GetNftUsingRateInfoResp
	nil,                                     // 23: GetInfoOfFriendHasUsingNftResp.UsingInfoMapEntry
	nil,                                     // 24: GetNftUsingRateInfoResp.NftUsingRateMapEntry
}
var file_player_battle_proto_depIdxs = []int32{
	1,  // 0: GetBestRecordOfFriendBattleReq.uidList:type_name -> UidWrapper
	4,  // 1: GetBestRecordOfFriendBattleResp.list:type_name -> BattleRecordOfFriend
	9,  // 2: GetNftTopNInfoResp.nftList:type_name -> NtfSimpleInfo
	13, // 3: GetRuneRateResp.runeRates:type_name -> RuneRate
	16, // 4: GetDefeatNftTopNInfoResp.defeatRates:type_name -> DefeatRate
	1,  // 5: GetInfoOfFriendHasUsingNftReq.uidList:type_name -> UidWrapper
	2,  // 6: GetInfoOfFriendHasUsingNftReq.nftIdList:type_name -> NftIdWrapper
	23, // 7: GetInfoOfFriendHasUsingNftResp.usingInfoMap:type_name -> GetInfoOfFriendHasUsingNftResp.UsingInfoMapEntry
	1,  // 8: FriendUidListOfUsingNft.uidList:type_name -> UidWrapper
	2,  // 9: GetNftUsingRateInfoReq.nftIdList:type_name -> NftIdWrapper
	24, // 10: GetNftUsingRateInfoResp.nftUsingRateMap:type_name -> GetNftUsingRateInfoResp.NftUsingRateMapEntry
	20, // 11: GetInfoOfFriendHasUsingNftResp.UsingInfoMapEntry.value:type_name -> FriendUidListOfUsingNft
	5,  // 12: PlayerBattleSvc.GetUserBattleInfo:input_type -> GetUserBattleInfoReq
	0,  // 13: PlayerBattleSvc.GetBestRecordOfFriendBattle:input_type -> GetBestRecordOfFriendBattleReq
	7,  // 14: PlayerBattleSvc.GetNftTopNInfo:input_type -> GetNftTopNInfoReq
	10, // 15: PlayerBattleSvc.GetSurpassRateByScore:input_type -> GetSurpassRateByScoreReq
	12, // 16: PlayerBattleSvc.GetRuneRate:input_type -> GetRuneRateReq
	15, // 17: PlayerBattleSvc.GetDefeatNftTopNInfo:input_type -> GetDefeatNftTopNInfoReq
	18, // 18: PlayerBattleSvc.GetInfoOfFriendHasUsingNft:input_type -> GetInfoOfFriendHasUsingNftReq
	21, // 19: PlayerBattleSvc.GetNftUsingRateInfo:input_type -> GetNftUsingRateInfoReq
	6,  // 20: PlayerBattleSvc.GetUserBattleInfo:output_type -> GetUserBattleInfoResp
	3,  // 21: PlayerBattleSvc.GetBestRecordOfFriendBattle:output_type -> GetBestRecordOfFriendBattleResp
	8,  // 22: PlayerBattleSvc.GetNftTopNInfo:output_type -> GetNftTopNInfoResp
	11, // 23: PlayerBattleSvc.GetSurpassRateByScore:output_type -> GetSurpassRateByScoreResp
	14, // 24: PlayerBattleSvc.GetRuneRate:output_type -> GetRuneRateResp
	17, // 25: PlayerBattleSvc.GetDefeatNftTopNInfo:output_type -> GetDefeatNftTopNInfoResp
	19, // 26: PlayerBattleSvc.GetInfoOfFriendHasUsingNft:output_type -> GetInfoOfFriendHasUsingNftResp
	22, // 27: PlayerBattleSvc.GetNftUsingRateInfo:output_type -> GetNftUsingRateInfoResp
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_player_battle_proto_init() }
func file_player_battle_proto_init() {
	if File_player_battle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_player_battle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBestRecordOfFriendBattleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UidWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NftIdWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBestRecordOfFriendBattleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleRecordOfFriend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBattleInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBattleInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNftTopNInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNftTopNInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NtfSimpleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSurpassRateByScoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSurpassRateByScoreResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRuneRateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuneRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRuneRateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDefeatNftTopNInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefeatRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDefeatNftTopNInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfoOfFriendHasUsingNftReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfoOfFriendHasUsingNftResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendUidListOfUsingNft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNftUsingRateInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_player_battle_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNftUsingRateInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_player_battle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_battle_proto_goTypes,
		DependencyIndexes: file_player_battle_proto_depIdxs,
		MessageInfos:      file_player_battle_proto_msgTypes,
	}.Build()
	File_player_battle_proto = out.File
	file_player_battle_proto_rawDesc = nil
	file_player_battle_proto_goTypes = nil
	file_player_battle_proto_depIdxs = nil
}
