// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: player_battle.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PlayerBattleSvc_GetUserBattleInfo_FullMethodName           = "/PlayerBattleSvc/GetUserBattleInfo"
	PlayerBattleSvc_GetBestRecordOfFriendBattle_FullMethodName = "/PlayerBattleSvc/GetBestRecordOfFriendBattle"
	PlayerBattleSvc_GetNftTopNInfo_FullMethodName              = "/PlayerBattleSvc/GetNftTopNInfo"
	PlayerBattleSvc_GetSurpassRateByScore_FullMethodName       = "/PlayerBattleSvc/GetSurpassRateByScore"
	PlayerBattleSvc_GetRuneRate_FullMethodName                 = "/PlayerBattleSvc/GetRuneRate"
	PlayerBattleSvc_GetDefeatNftTopNInfo_FullMethodName        = "/PlayerBattleSvc/GetDefeatNftTopNInfo"
	PlayerBattleSvc_GetInfoOfFriendHasUsingNft_FullMethodName  = "/PlayerBattleSvc/GetInfoOfFriendHasUsingNft"
	PlayerBattleSvc_GetNftUsingRateInfo_FullMethodName         = "/PlayerBattleSvc/GetNftUsingRateInfo"
)

// PlayerBattleSvcClient is the client API for PlayerBattleSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerBattleSvcClient interface {
	// 获取用户当前对战信息，对战的游戏，和 battleId
	GetUserBattleInfo(ctx context.Context, in *GetUserBattleInfoReq, opts ...grpc.CallOption) (*GetUserBattleInfoResp, error)
	// 查询好友的历史最高对战记录
	GetBestRecordOfFriendBattle(ctx context.Context, in *GetBestRecordOfFriendBattleReq, opts ...grpc.CallOption) (*GetBestRecordOfFriendBattleResp, error)
	// 获取nft出场率排行相关数据
	GetNftTopNInfo(ctx context.Context, in *GetNftTopNInfoReq, opts ...grpc.CallOption) (*GetNftTopNInfoResp, error)
	// 根据当前成绩获取超越玩家的百分比(跑酷)
	GetSurpassRateByScore(ctx context.Context, in *GetSurpassRateByScoreReq, opts ...grpc.CallOption) (*GetSurpassRateByScoreResp, error)
	// 获得各种符文的记录在所有对局记录里的占比（包括未获得记录条）（捕鱼)
	GetRuneRate(ctx context.Context, in *GetRuneRateReq, opts ...grpc.CallOption) (*GetRuneRateResp, error)
	// pvp,战胜对手NFT最多次数的NFT角色
	GetDefeatNftTopNInfo(ctx context.Context, in *GetDefeatNftTopNInfoReq, opts ...grpc.CallOption) (*GetDefeatNftTopNInfoResp, error)
	// 查询好友是否在一个游戏中使用过某几个 nft todo
	GetInfoOfFriendHasUsingNft(ctx context.Context, in *GetInfoOfFriendHasUsingNftReq, opts ...grpc.CallOption) (*GetInfoOfFriendHasUsingNftResp, error)
	// 查询 nft 的使用率信息
	GetNftUsingRateInfo(ctx context.Context, in *GetNftUsingRateInfoReq, opts ...grpc.CallOption) (*GetNftUsingRateInfoResp, error)
}

type playerBattleSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerBattleSvcClient(cc grpc.ClientConnInterface) PlayerBattleSvcClient {
	return &playerBattleSvcClient{cc}
}

func (c *playerBattleSvcClient) GetUserBattleInfo(ctx context.Context, in *GetUserBattleInfoReq, opts ...grpc.CallOption) (*GetUserBattleInfoResp, error) {
	out := new(GetUserBattleInfoResp)
	err := c.cc.Invoke(ctx, PlayerBattleSvc_GetUserBattleInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerBattleSvcClient) GetBestRecordOfFriendBattle(ctx context.Context, in *GetBestRecordOfFriendBattleReq, opts ...grpc.CallOption) (*GetBestRecordOfFriendBattleResp, error) {
	out := new(GetBestRecordOfFriendBattleResp)
	err := c.cc.Invoke(ctx, PlayerBattleSvc_GetBestRecordOfFriendBattle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerBattleSvcClient) GetNftTopNInfo(ctx context.Context, in *GetNftTopNInfoReq, opts ...grpc.CallOption) (*GetNftTopNInfoResp, error) {
	out := new(GetNftTopNInfoResp)
	err := c.cc.Invoke(ctx, PlayerBattleSvc_GetNftTopNInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerBattleSvcClient) GetSurpassRateByScore(ctx context.Context, in *GetSurpassRateByScoreReq, opts ...grpc.CallOption) (*GetSurpassRateByScoreResp, error) {
	out := new(GetSurpassRateByScoreResp)
	err := c.cc.Invoke(ctx, PlayerBattleSvc_GetSurpassRateByScore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerBattleSvcClient) GetRuneRate(ctx context.Context, in *GetRuneRateReq, opts ...grpc.CallOption) (*GetRuneRateResp, error) {
	out := new(GetRuneRateResp)
	err := c.cc.Invoke(ctx, PlayerBattleSvc_GetRuneRate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerBattleSvcClient) GetDefeatNftTopNInfo(ctx context.Context, in *GetDefeatNftTopNInfoReq, opts ...grpc.CallOption) (*GetDefeatNftTopNInfoResp, error) {
	out := new(GetDefeatNftTopNInfoResp)
	err := c.cc.Invoke(ctx, PlayerBattleSvc_GetDefeatNftTopNInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerBattleSvcClient) GetInfoOfFriendHasUsingNft(ctx context.Context, in *GetInfoOfFriendHasUsingNftReq, opts ...grpc.CallOption) (*GetInfoOfFriendHasUsingNftResp, error) {
	out := new(GetInfoOfFriendHasUsingNftResp)
	err := c.cc.Invoke(ctx, PlayerBattleSvc_GetInfoOfFriendHasUsingNft_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerBattleSvcClient) GetNftUsingRateInfo(ctx context.Context, in *GetNftUsingRateInfoReq, opts ...grpc.CallOption) (*GetNftUsingRateInfoResp, error) {
	out := new(GetNftUsingRateInfoResp)
	err := c.cc.Invoke(ctx, PlayerBattleSvc_GetNftUsingRateInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerBattleSvcServer is the server API for PlayerBattleSvc service.
// All implementations must embed UnimplementedPlayerBattleSvcServer
// for forward compatibility
type PlayerBattleSvcServer interface {
	// 获取用户当前对战信息，对战的游戏，和 battleId
	GetUserBattleInfo(context.Context, *GetUserBattleInfoReq) (*GetUserBattleInfoResp, error)
	// 查询好友的历史最高对战记录
	GetBestRecordOfFriendBattle(context.Context, *GetBestRecordOfFriendBattleReq) (*GetBestRecordOfFriendBattleResp, error)
	// 获取nft出场率排行相关数据
	GetNftTopNInfo(context.Context, *GetNftTopNInfoReq) (*GetNftTopNInfoResp, error)
	// 根据当前成绩获取超越玩家的百分比(跑酷)
	GetSurpassRateByScore(context.Context, *GetSurpassRateByScoreReq) (*GetSurpassRateByScoreResp, error)
	// 获得各种符文的记录在所有对局记录里的占比（包括未获得记录条）（捕鱼)
	GetRuneRate(context.Context, *GetRuneRateReq) (*GetRuneRateResp, error)
	// pvp,战胜对手NFT最多次数的NFT角色
	GetDefeatNftTopNInfo(context.Context, *GetDefeatNftTopNInfoReq) (*GetDefeatNftTopNInfoResp, error)
	// 查询好友是否在一个游戏中使用过某几个 nft todo
	GetInfoOfFriendHasUsingNft(context.Context, *GetInfoOfFriendHasUsingNftReq) (*GetInfoOfFriendHasUsingNftResp, error)
	// 查询 nft 的使用率信息
	GetNftUsingRateInfo(context.Context, *GetNftUsingRateInfoReq) (*GetNftUsingRateInfoResp, error)
	mustEmbedUnimplementedPlayerBattleSvcServer()
}

// UnimplementedPlayerBattleSvcServer must be embedded to have forward compatible implementations.
type UnimplementedPlayerBattleSvcServer struct {
}

func (UnimplementedPlayerBattleSvcServer) GetUserBattleInfo(context.Context, *GetUserBattleInfoReq) (*GetUserBattleInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBattleInfo not implemented")
}
func (UnimplementedPlayerBattleSvcServer) GetBestRecordOfFriendBattle(context.Context, *GetBestRecordOfFriendBattleReq) (*GetBestRecordOfFriendBattleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBestRecordOfFriendBattle not implemented")
}
func (UnimplementedPlayerBattleSvcServer) GetNftTopNInfo(context.Context, *GetNftTopNInfoReq) (*GetNftTopNInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNftTopNInfo not implemented")
}
func (UnimplementedPlayerBattleSvcServer) GetSurpassRateByScore(context.Context, *GetSurpassRateByScoreReq) (*GetSurpassRateByScoreResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSurpassRateByScore not implemented")
}
func (UnimplementedPlayerBattleSvcServer) GetRuneRate(context.Context, *GetRuneRateReq) (*GetRuneRateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuneRate not implemented")
}
func (UnimplementedPlayerBattleSvcServer) GetDefeatNftTopNInfo(context.Context, *GetDefeatNftTopNInfoReq) (*GetDefeatNftTopNInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefeatNftTopNInfo not implemented")
}
func (UnimplementedPlayerBattleSvcServer) GetInfoOfFriendHasUsingNft(context.Context, *GetInfoOfFriendHasUsingNftReq) (*GetInfoOfFriendHasUsingNftResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfoOfFriendHasUsingNft not implemented")
}
func (UnimplementedPlayerBattleSvcServer) GetNftUsingRateInfo(context.Context, *GetNftUsingRateInfoReq) (*GetNftUsingRateInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNftUsingRateInfo not implemented")
}
func (UnimplementedPlayerBattleSvcServer) mustEmbedUnimplementedPlayerBattleSvcServer() {}

// UnsafePlayerBattleSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerBattleSvcServer will
// result in compilation errors.
type UnsafePlayerBattleSvcServer interface {
	mustEmbedUnimplementedPlayerBattleSvcServer()
}

func RegisterPlayerBattleSvcServer(s grpc.ServiceRegistrar, srv PlayerBattleSvcServer) {
	s.RegisterService(&PlayerBattleSvc_ServiceDesc, srv)
}

func _PlayerBattleSvc_GetUserBattleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBattleInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerBattleSvcServer).GetUserBattleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerBattleSvc_GetUserBattleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerBattleSvcServer).GetUserBattleInfo(ctx, req.(*GetUserBattleInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerBattleSvc_GetBestRecordOfFriendBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBestRecordOfFriendBattleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerBattleSvcServer).GetBestRecordOfFriendBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerBattleSvc_GetBestRecordOfFriendBattle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerBattleSvcServer).GetBestRecordOfFriendBattle(ctx, req.(*GetBestRecordOfFriendBattleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerBattleSvc_GetNftTopNInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNftTopNInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerBattleSvcServer).GetNftTopNInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerBattleSvc_GetNftTopNInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerBattleSvcServer).GetNftTopNInfo(ctx, req.(*GetNftTopNInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerBattleSvc_GetSurpassRateByScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSurpassRateByScoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerBattleSvcServer).GetSurpassRateByScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerBattleSvc_GetSurpassRateByScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerBattleSvcServer).GetSurpassRateByScore(ctx, req.(*GetSurpassRateByScoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerBattleSvc_GetRuneRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuneRateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerBattleSvcServer).GetRuneRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerBattleSvc_GetRuneRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerBattleSvcServer).GetRuneRate(ctx, req.(*GetRuneRateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerBattleSvc_GetDefeatNftTopNInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefeatNftTopNInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerBattleSvcServer).GetDefeatNftTopNInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerBattleSvc_GetDefeatNftTopNInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerBattleSvcServer).GetDefeatNftTopNInfo(ctx, req.(*GetDefeatNftTopNInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerBattleSvc_GetInfoOfFriendHasUsingNft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoOfFriendHasUsingNftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerBattleSvcServer).GetInfoOfFriendHasUsingNft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerBattleSvc_GetInfoOfFriendHasUsingNft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerBattleSvcServer).GetInfoOfFriendHasUsingNft(ctx, req.(*GetInfoOfFriendHasUsingNftReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerBattleSvc_GetNftUsingRateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNftUsingRateInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerBattleSvcServer).GetNftUsingRateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerBattleSvc_GetNftUsingRateInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerBattleSvcServer).GetNftUsingRateInfo(ctx, req.(*GetNftUsingRateInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerBattleSvc_ServiceDesc is the grpc.ServiceDesc for PlayerBattleSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerBattleSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PlayerBattleSvc",
	HandlerType: (*PlayerBattleSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserBattleInfo",
			Handler:    _PlayerBattleSvc_GetUserBattleInfo_Handler,
		},
		{
			MethodName: "GetBestRecordOfFriendBattle",
			Handler:    _PlayerBattleSvc_GetBestRecordOfFriendBattle_Handler,
		},
		{
			MethodName: "GetNftTopNInfo",
			Handler:    _PlayerBattleSvc_GetNftTopNInfo_Handler,
		},
		{
			MethodName: "GetSurpassRateByScore",
			Handler:    _PlayerBattleSvc_GetSurpassRateByScore_Handler,
		},
		{
			MethodName: "GetRuneRate",
			Handler:    _PlayerBattleSvc_GetRuneRate_Handler,
		},
		{
			MethodName: "GetDefeatNftTopNInfo",
			Handler:    _PlayerBattleSvc_GetDefeatNftTopNInfo_Handler,
		},
		{
			MethodName: "GetInfoOfFriendHasUsingNft",
			Handler:    _PlayerBattleSvc_GetInfoOfFriendHasUsingNft_Handler,
		},
		{
			MethodName: "GetNftUsingRateInfo",
			Handler:    _PlayerBattleSvc_GetNftUsingRateInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player_battle.proto",
}
