// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: user_info.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserInfoSvc_GetUserInfo_FullMethodName = "/UserInfoSvc/GetUserInfo"
)

// UserInfoSvcClient is the client API for UserInfoSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserInfoSvcClient interface {
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
}

type userInfoSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInfoSvcClient(cc grpc.ClientConnInterface) UserInfoSvcClient {
	return &userInfoSvcClient{cc}
}

func (c *userInfoSvcClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, UserInfoSvc_GetUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInfoSvcServer is the server API for UserInfoSvc service.
// All implementations must embed UnimplementedUserInfoSvcServer
// for forward compatibility
type UserInfoSvcServer interface {
	// 获取用户信息
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error)
	mustEmbedUnimplementedUserInfoSvcServer()
}

// UnimplementedUserInfoSvcServer must be embedded to have forward compatible implementations.
type UnimplementedUserInfoSvcServer struct {
}

func (UnimplementedUserInfoSvcServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserInfoSvcServer) mustEmbedUnimplementedUserInfoSvcServer() {}

// UnsafeUserInfoSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserInfoSvcServer will
// result in compilation errors.
type UnsafeUserInfoSvcServer interface {
	mustEmbedUnimplementedUserInfoSvcServer()
}

func RegisterUserInfoSvcServer(s grpc.ServiceRegistrar, srv UserInfoSvcServer) {
	s.RegisterService(&UserInfoSvc_ServiceDesc, srv)
}

func _UserInfoSvc_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoSvcServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserInfoSvc_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoSvcServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserInfoSvc_ServiceDesc is the grpc.ServiceDesc for UserInfoSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserInfoSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserInfoSvc",
	HandlerType: (*UserInfoSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _UserInfoSvc_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_info.proto",
}
