// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: game.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameSvc_CreateMatch_FullMethodName       = "/GameSvc/CreateMatch"
	GameSvc_CheckCanReconnect_FullMethodName = "/GameSvc/CheckCanReconnect"
	GameSvc_PlayerExit_FullMethodName        = "/GameSvc/PlayerExit"
)

// GameSvcClient is the client API for GameSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameSvcClient interface {
	// 创建对局
	CreateMatch(ctx context.Context, in *CreateMatchReq, opts ...grpc.CallOption) (*CreateMatchResp, error)
	// 检查游戏对局是否能重连/重新进入。如果对局结束，则不能进入
	CheckCanReconnect(ctx context.Context, in *CheckCanReconnectReq, opts ...grpc.CallOption) (*CheckCanReconnectResp, error)
	// 玩家投降，退出游戏
	PlayerExit(ctx context.Context, in *PlayerExitReq, opts ...grpc.CallOption) (*PlayerExitResp, error)
}

type gameSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewGameSvcClient(cc grpc.ClientConnInterface) GameSvcClient {
	return &gameSvcClient{cc}
}

func (c *gameSvcClient) CreateMatch(ctx context.Context, in *CreateMatchReq, opts ...grpc.CallOption) (*CreateMatchResp, error) {
	out := new(CreateMatchResp)
	err := c.cc.Invoke(ctx, GameSvc_CreateMatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSvcClient) CheckCanReconnect(ctx context.Context, in *CheckCanReconnectReq, opts ...grpc.CallOption) (*CheckCanReconnectResp, error) {
	out := new(CheckCanReconnectResp)
	err := c.cc.Invoke(ctx, GameSvc_CheckCanReconnect_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameSvcClient) PlayerExit(ctx context.Context, in *PlayerExitReq, opts ...grpc.CallOption) (*PlayerExitResp, error) {
	out := new(PlayerExitResp)
	err := c.cc.Invoke(ctx, GameSvc_PlayerExit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameSvcServer is the server API for GameSvc service.
// All implementations must embed UnimplementedGameSvcServer
// for forward compatibility
type GameSvcServer interface {
	// 创建对局
	CreateMatch(context.Context, *CreateMatchReq) (*CreateMatchResp, error)
	// 检查游戏对局是否能重连/重新进入。如果对局结束，则不能进入
	CheckCanReconnect(context.Context, *CheckCanReconnectReq) (*CheckCanReconnectResp, error)
	// 玩家投降，退出游戏
	PlayerExit(context.Context, *PlayerExitReq) (*PlayerExitResp, error)
	mustEmbedUnimplementedGameSvcServer()
}

// UnimplementedGameSvcServer must be embedded to have forward compatible implementations.
type UnimplementedGameSvcServer struct {
}

func (UnimplementedGameSvcServer) CreateMatch(context.Context, *CreateMatchReq) (*CreateMatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMatch not implemented")
}
func (UnimplementedGameSvcServer) CheckCanReconnect(context.Context, *CheckCanReconnectReq) (*CheckCanReconnectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCanReconnect not implemented")
}
func (UnimplementedGameSvcServer) PlayerExit(context.Context, *PlayerExitReq) (*PlayerExitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerExit not implemented")
}
func (UnimplementedGameSvcServer) mustEmbedUnimplementedGameSvcServer() {}

// UnsafeGameSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameSvcServer will
// result in compilation errors.
type UnsafeGameSvcServer interface {
	mustEmbedUnimplementedGameSvcServer()
}

func RegisterGameSvcServer(s grpc.ServiceRegistrar, srv GameSvcServer) {
	s.RegisterService(&GameSvc_ServiceDesc, srv)
}

func _GameSvc_CreateMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSvcServer).CreateMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSvc_CreateMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSvcServer).CreateMatch(ctx, req.(*CreateMatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSvc_CheckCanReconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCanReconnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSvcServer).CheckCanReconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSvc_CheckCanReconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSvcServer).CheckCanReconnect(ctx, req.(*CheckCanReconnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameSvc_PlayerExit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerExitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameSvcServer).PlayerExit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameSvc_PlayerExit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameSvcServer).PlayerExit(ctx, req.(*PlayerExitReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameSvc_ServiceDesc is the grpc.ServiceDesc for GameSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GameSvc",
	HandlerType: (*GameSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMatch",
			Handler:    _GameSvc_CreateMatch_Handler,
		},
		{
			MethodName: "CheckCanReconnect",
			Handler:    _GameSvc_CheckCanReconnect_Handler,
		},
		{
			MethodName: "PlayerExit",
			Handler:    _GameSvc_PlayerExit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
