// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: game.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameType int32

const (
	GameType_GameTypePve     GameType = 0 // pve
	GameType_GameTypePvP_1v1 GameType = 1 // pvp 1v1
	GameType_GameTypePvP_1vn GameType = 2 // pvp 1vN
	GameType_GameTypeKnock   GameType = 3 // 淘汰赛
)

// Enum value maps for GameType.
var (
	GameType_name = map[int32]string{
		0: "GameTypePve",
		1: "GameTypePvP_1v1",
		2: "GameTypePvP_1vn",
		3: "GameTypeKnock",
	}
	GameType_value = map[string]int32{
		"GameTypePve":     0,
		"GameTypePvP_1v1": 1,
		"GameTypePvP_1vn": 2,
		"GameTypeKnock":   3,
	}
)

func (x GameType) Enum() *GameType {
	p := new(GameType)
	*p = x
	return p
}

func (x GameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (GameType) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x GameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameType.Descriptor instead.
func (GameType) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

type CreateMatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 对局 id | @inject_tag: msgpack:"battleId" json:"battleId"
	BattleId int32 `protobuf:"varint,2,opt,name=battleId,proto3" json:"battleId" msgpack:"battleId"`
	// 模式 | @inject_tag: msgpack:"mode" json:"mode"
	Mode string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode" msgpack:"mode"`
	// 对局中，队伍的数量 | @inject_tag: msgpack:"teamNum" json:"teamNum"
	TeamNum int32 `protobuf:"varint,4,opt,name=teamNum,proto3" json:"teamNum" msgpack:"teamNum"`
	// 每个队伍中，玩家的数量 | @inject_tag: msgpack:"playersPerTeam" json:"playersPerTeam"
	PlayersPerTeam int32 `protobuf:"varint,5,opt,name=playersPerTeam,proto3" json:"playersPerTeam" msgpack:"playersPerTeam"`
	// 关卡 | @inject_tag: msgpack:"stage" json:"stage"
	Stage int32 `protobuf:"varint,6,opt,name=stage,proto3" json:"stage" msgpack:"stage"`
	// 游戏的玩家信息 | @inject_tag: msgpack:"players" json:"players"
	Players []*CreateMatchReqPlayer `protobuf:"bytes,7,rep,name=players,proto3" json:"players" msgpack:"players"`
	// 对局难度，部分游戏支持 | @inject_tag: msgpack:"difficulty" json:"difficulty"
	Difficulty int32 `protobuf:"varint,8,opt,name=difficulty,proto3" json:"difficulty" msgpack:"difficulty"`
	// 创建对局后，如果玩家未连接，等待一定秒数，游戏自动开始 | @inject_tag: msgpack:"timeout" json:"timeout"
	Timeout int32 `protobuf:"varint,9,opt,name=timeout,proto3" json:"timeout" msgpack:"timeout"`
	// 对局类型，0:pve，1:1v1，2:1vn，3:淘汰赛 | @inject_tag: msgpack:"gameType" json:"gameType"
	GameType GameType `protobuf:"varint,10,opt,name=gameType,proto3,enum=GameType" json:"gameType" msgpack:"gameType"`
}

func (x *CreateMatchReq) Reset() {
	*x = CreateMatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMatchReq) ProtoMessage() {}

func (x *CreateMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMatchReq.ProtoReflect.Descriptor instead.
func (*CreateMatchReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMatchReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *CreateMatchReq) GetBattleId() int32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *CreateMatchReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateMatchReq) GetTeamNum() int32 {
	if x != nil {
		return x.TeamNum
	}
	return 0
}

func (x *CreateMatchReq) GetPlayersPerTeam() int32 {
	if x != nil {
		return x.PlayersPerTeam
	}
	return 0
}

func (x *CreateMatchReq) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *CreateMatchReq) GetPlayers() []*CreateMatchReqPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *CreateMatchReq) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *CreateMatchReq) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CreateMatchReq) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_GameTypePve
}

type CreateMatchReqPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 玩家 token | @inject_tag: msgpack:"token" json:"token"
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token" msgpack:"token"`
	// 是否是机器人 | @inject_tag: msgpack:"isRobot" json:"isRobot"
	IsRobot bool `protobuf:"varint,2,opt,name=isRobot,proto3" json:"isRobot" msgpack:"isRobot"`
	// 机器人级别 | @inject_tag: msgpack:"robotLevel" json:"robotLevel"
	RobotLevel int32 `protobuf:"varint,3,opt,name=robotLevel,proto3" json:"robotLevel" msgpack:"robotLevel"`
	// 玩家的 uid | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
	// 玩家的选择的 nft 列表 | @inject_tag: msgpack:"legends" json:"legends"
	Legends []string `protobuf:"bytes,5,rep,name=legends,proto3" json:"legends" msgpack:"legends"`
}

func (x *CreateMatchReqPlayer) Reset() {
	*x = CreateMatchReqPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMatchReqPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMatchReqPlayer) ProtoMessage() {}

func (x *CreateMatchReqPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMatchReqPlayer.ProtoReflect.Descriptor instead.
func (*CreateMatchReqPlayer) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMatchReqPlayer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateMatchReqPlayer) GetIsRobot() bool {
	if x != nil {
		return x.IsRobot
	}
	return false
}

func (x *CreateMatchReqPlayer) GetRobotLevel() int32 {
	if x != nil {
		return x.RobotLevel
	}
	return 0
}

func (x *CreateMatchReqPlayer) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CreateMatchReqPlayer) GetLegends() []string {
	if x != nil {
		return x.Legends
	}
	return nil
}

type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
	// 数据 | @inject_tag: msgpack:"data" json:"data"
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data" msgpack:"data"`
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateMatchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
	// 数据 | @inject_tag: msgpack:"data" json:"data"
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data" msgpack:"data"`
}

func (x *CreateMatchResp) Reset() {
	*x = CreateMatchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMatchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMatchResp) ProtoMessage() {}

func (x *CreateMatchResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMatchResp.ProtoReflect.Descriptor instead.
func (*CreateMatchResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMatchResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateMatchResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateMatchResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckCanReconnectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 对局 id | @inject_tag: msgpack:"battleId" json:"battleId"
	BattleId int64 `protobuf:"varint,2,opt,name=battleId,proto3" json:"battleId" msgpack:"battleId"`
}

func (x *CheckCanReconnectReq) Reset() {
	*x = CheckCanReconnectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCanReconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCanReconnectReq) ProtoMessage() {}

func (x *CheckCanReconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCanReconnectReq.ProtoReflect.Descriptor instead.
func (*CheckCanReconnectReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *CheckCanReconnectReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *CheckCanReconnectReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

type CheckCanReconnectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
	// 是否能重连 | @inject_tag: msgpack:"couldConn" json:"couldConn"
	CouldConn bool `protobuf:"varint,3,opt,name=couldConn,proto3" json:"couldConn" msgpack:"couldConn"`
}

func (x *CheckCanReconnectResp) Reset() {
	*x = CheckCanReconnectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCanReconnectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCanReconnectResp) ProtoMessage() {}

func (x *CheckCanReconnectResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCanReconnectResp.ProtoReflect.Descriptor instead.
func (*CheckCanReconnectResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *CheckCanReconnectResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckCanReconnectResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckCanReconnectResp) GetCouldConn() bool {
	if x != nil {
		return x.CouldConn
	}
	return false
}

type PlayerExitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 游戏标识 | @inject_tag: msgpack:"gameId" json:"gameId"
	GameId int32 `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId" msgpack:"gameId"`
	// 对局 id | @inject_tag: msgpack:"battleId" json:"battleId"
	BattleId int64 `protobuf:"varint,2,opt,name=battleId,proto3" json:"battleId" msgpack:"battleId"`
	// 玩家 | @inject_tag: msgpack:"uid" json:"uid"
	Uid string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid" msgpack:"uid"`
}

func (x *PlayerExitReq) Reset() {
	*x = PlayerExitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerExitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerExitReq) ProtoMessage() {}

func (x *PlayerExitReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerExitReq.ProtoReflect.Descriptor instead.
func (*PlayerExitReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerExitReq) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *PlayerExitReq) GetBattleId() int64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *PlayerExitReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type PlayerExitResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 200: 成功；非 200 表示异常 | @inject_tag: msgpack:"code" json:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" msgpack:"code"`
	// 备注 | @inject_tag: msgpack:"message" json:"message"
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message" msgpack:"message"`
}

func (x *PlayerExitResp) Reset() {
	*x = PlayerExitResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerExitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerExitResp) ProtoMessage() {}

func (x *PlayerExitResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerExitResp.ProtoReflect.Descriptor instead.
func (*PlayerExitResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerExitResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PlayerExitResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x02, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x4e,
	0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x4e, 0x75,
	0x6d, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x50, 0x65, 0x72, 0x54,
	0x65, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x50, 0x65, 0x72, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12,
	0x2f, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x92, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x65, 0x67, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x65, 0x67, 0x65, 0x6e, 0x64, 0x73, 0x22, 0x4e, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x53, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x14, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x43, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x43, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x22, 0x55, 0x0a, 0x0d,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2a, 0x58, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0f, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x76, 0x65, 0x10, 0x00,
	0x12, 0x13, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x76, 0x50, 0x5f,
	0x31, 0x76, 0x31, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x50, 0x76, 0x50, 0x5f, 0x31, 0x76, 0x6e, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4b, 0x6e, 0x6f, 0x63, 0x6b, 0x10, 0x03, 0x32, 0xb4, 0x01,
	0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x76, 0x63, 0x12, 0x32, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x0f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x44, 0x0a,
	0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x12, 0x15, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x61, 0x6e, 0x52, 0x65, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x43, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x69,
	0x74, 0x12, 0x0e, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x42, 0x60, 0x5a, 0x5e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x68, 0x61, 0x6e, 0x79, 0x75, 0x6a, 0x69, 0x65, 0x2f, 0x67, 0x6f,
	0x5f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x76, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x2f, 0x70, 0x62, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_game_proto_goTypes = []interface{}{
	(GameType)(0),                 // 0: GameType
	(*CreateMatchReq)(nil),        // 1: CreateMatchReq
	(*CreateMatchReqPlayer)(nil),  // 2: CreateMatchReqPlayer
	(*CommonResp)(nil),            // 3: CommonResp
	(*CreateMatchResp)(nil),       // 4: CreateMatchResp
	(*CheckCanReconnectReq)(nil),  // 5: CheckCanReconnectReq
	(*CheckCanReconnectResp)(nil), // 6: CheckCanReconnectResp
	(*PlayerExitReq)(nil),         // 7: PlayerExitReq
	(*PlayerExitResp)(nil),        // 8: PlayerExitResp
}
var file_game_proto_depIdxs = []int32{
	2, // 0: CreateMatchReq.players:type_name -> CreateMatchReqPlayer
	0, // 1: CreateMatchReq.gameType:type_name -> GameType
	1, // 2: GameSvc.CreateMatch:input_type -> CreateMatchReq
	5, // 3: GameSvc.CheckCanReconnect:input_type -> CheckCanReconnectReq
	7, // 4: GameSvc.PlayerExit:input_type -> PlayerExitReq
	4, // 5: GameSvc.CreateMatch:output_type -> CreateMatchResp
	6, // 6: GameSvc.CheckCanReconnect:output_type -> CheckCanReconnectResp
	8, // 7: GameSvc.PlayerExit:output_type -> PlayerExitResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMatchReqPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMatchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCanReconnectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCanReconnectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerExitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerExitResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_rawDesc = nil
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
